### ISSUE TITLE
problems getting dashboard addon working

### ISSUE THREAD

**Issue by chrisroat** [ubuntu/microk8s#1158]
[inspection-report-20200427_172851.tar.gz](https://github.com/ubuntu/microk8s/files/4542716/inspection-report-20200427_172851.tar.gz)

I am just getting started with microk8s on an Ubuntu 18.04 workstation that I'd like to do some cluster testing on.  I've done the getting started, and have moved on to the dashboard addon.   The port-forward command runs, but gives errors and nothing is serving on localhost.

What I notice is coredns is running, but not ready.  Then, at some point, hostpath-provisioner and kubernetes-dashboard start erroring or crashlooping.

I've gone through several issues at this point, doing the suggested ufw commands, and installing/re-installing,   But still the same result.

Is there any clue in the inspection report?

Example hostpath-provisioner log
```
F0428 00:32:15.028585       1 hostpath-provisioner.go:162] Error getting server version: Get https://10.152.183.1:443/version: dial tcp 10.152.183.1:443: i/o timeout
```

Example kubernetes-dashboard log
```
panic: Get https://10.152.183.1:443/api/v1/namespaces/kube-system/secrets/kubernetes-dashboard-csrf: dial tcp 10.152.183.1:443: i/o timeout

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc0005388c0)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:40 +0x3b4
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:65
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc0001b6080)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:494 +0xc7
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc0001b6080)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:462 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
	/home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:543
main.main()
	/home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x212
```

**Comment by chrisroat** [comment]
I ended up just shutting off ufw, thought that's not a great long-term solution.  When it was active, I did have cni0 open:
```bash
$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
Anywhere on docker0        ALLOW       Anywhere                  
Anywhere on cni0           ALLOW       Anywhere                  
Anywhere on cbr0           ALLOW       Anywhere                  
Anywhere (v6) on docker0   ALLOW       Anywhere (v6)             
Anywhere (v6) on cni0      ALLOW       Anywhere (v6)             
Anywhere (v6) on cbr0      ALLOW       Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on cni0          
Anywhere                   ALLOW OUT   Anywhere on cbr0          
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on cni0     
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on cbr0     
```
