### ISSUE TITLE
error using DNS address in --etcd-endpoints in flannel args

### ISSUE THREAD

**Issue by carlosrmendes** [ubuntu/microk8s#1175]
my `/var/snap/microk8s/current/args/flanneld` file:
```
--iface=""
--etcd-endpoints https://master.example.internal:12379
--etcd-cafile ${SNAP_DATA}/certs/ca.remote.crt
--etcd-certfile ${SNAP_DATA}/certs/server.remote.crt
--etcd-keyfile ${SNAP_DATA}/certs/server.key
--subnet-file=${SNAP_COMMON}/run/flannel/subnet.env
```

`snap.microk8s.daemon-flanneld service` log:
```
May 02 18:10:32 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: PrevNode.Value: {"Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: {"Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: I0502 18:10:33.241350   31518 main.go:514] Determining IP address of default interface
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: I0502 18:10:33.241702   31518 main.go:527] Using interface with name ens5 and address 10.10.11.49
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: I0502 18:10:33.241721   31518 main.go:544] Defaulting external address to interface address (10.10.11.49)
May 02 18:10:33 ip-10-10-11-49 flanneld[31518]: warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: I0502 18:10:33.242285   31518 main.go:244] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.1.12.0/24
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: I0502 18:10:33.242294   31518 main.go:247] Installing signal handlers
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: fatal error: unexpected signal during runtime execution
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fb19013e448]
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime stack:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.throw(0x19a3a14, 0x2a)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/panic.go:616 +0x81
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.sigpanic()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/signal_unix.go:372 +0x28e
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 10 [syscall]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.cgocall(0x1441ee0, 0xc420058df8, 0x29)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420058db8 sp=0xc420058d80 pc=0x402304
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net._C2func_getaddrinfo(0xc42033fe60, 0x0, 0xc4203cfc50, 0xc4200ae570, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         _cgo_gotypes.go:86 +0x55 fp=0xc420058df8 sp=0xc420058db8 pc=0x51d535
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.cgoLookupIPCNAME.func1(0xc42033fe60, 0x0, 0xc4203cfc50, 0xc4200ae570, 0x12, 0x12, 0xc4200b2040)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/cgo_unix.go:149 +0x13b fp=0xc420058e40 sp=0xc420058df8 pc=0x52429b
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.cgoLookupIPCNAME(0xc42033f900, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/cgo_unix.go:149 +0x174 fp=0xc420058f38 sp=0xc420058e40 pc=0x51eba4
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.cgoIPLookup(0xc4200885a0, 0xc42033f900, 0x11)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/cgo_unix.go:201 +0x4d fp=0xc420058fc8 sp=0xc420058f38 pc=0x51f26d
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.goexit()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420058fd0 sp=0xc420058fc8 pc=0x456f71
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by net.cgoLookupIP
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/cgo_unix.go:211 +0xaf
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 1 [select]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do(0xc4202852c0, 0x7fb190104260, 0xc42022f000, 0x1acb460, 0xc4203cf410, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:531 +0x2e9
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*redirectFollowingHTTPClient).Do(0xc4202c4980, 0x7fb190104260, 0xc42022f000, 0x1acb460, 0xc4203cf410, 0x7ffc8ada5a5d, 0x17, 0x0, 0x0, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:603 +0xad
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpClusterClient).Do(0xc4202fbd40, 0x7fb190104260, 0xc42022f000, 0x1acb460, 0xc4203cf410, 0xc4205fdab0, 0x4115e8, 0x3, 0x17cbba0, 0xc4203ce401, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:360 +0x346
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*httpKeysAPI).Get(0xc4202c4920, 0x7fb190104260, 0xc42022f000, 0xc42033f880, 0x1a, 0xc4204443a8, 0x44e3a3, 0x17bf4e0, 0xc40000a258)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/keys.go:422 +0xd9
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/subnet/etcdv2.(*etcdSubnetRegistry).getNetworkConfig(0xc4203ce4e0, 0x7fb190104260, 0xc42022f000, 0x40, 0x3f, 0xc4205fdbd8, 0x410895)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/subnet/etcdv2/registry.go:117 +0x125
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/subnet/etcdv2.(*LocalManager).GetNetworkConfig(0xc4202c4940, 0x7fb190104260, 0xc42022f000, 0x7fb1918b1280, 0xc4205fdc38, 0x40e114)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/subnet/etcdv2/local_manager.go:88 +0x4b
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: main.getConfig(0x7fb190104260, 0xc42022f000, 0x1ae4ea0, 0xc4202c4940, 0xc4202fbda0, 0xc4204533b0, 0xc4204443f0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/main.go:380 +0xa8
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: main.main()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/main.go:271 +0x528
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 19 [syscall]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: os/signal.signal_recv(0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: os/signal.loop()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by os/signal.init.0
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 20 [chan receive]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x27a1f40)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x8b
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 5 [select, locked to thread]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.gopark(0x19f75b0, 0x0, 0x197b171, 0x6, 0x18, 0x1)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/proc.go:291 +0x11a
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.selectgo(0xc420057f50, 0xc4200924e0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/select.go:392 +0xe50
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.ensureSigM.func1()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: runtime.goexit()
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 6 [runnable]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: main.main.func1(0x7fb190104260, 0xc42022f000, 0xc4202fbda0, 0xc4204533b0, 0xc4204443f0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/main.go:260
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by main.main
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/main.go:260 +0x4e6
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 7 [select]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net/http.(*Transport).getConn(0xc4204ac000, 0xc4203cf590, 0x0, 0xc4202382a0, 0x5, 0xc42033f900, 0x17, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:962 +0x558
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net/http.(*Transport).RoundTrip(0xc4204ac000, 0xc420148e00, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:409 +0x632
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do.func1(0xc4202852c0, 0xc420148e00, 0xc4202fbec0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:523 +0x41
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by github.com/coreos/flannel/vendor/github.com/coreos/etcd/client.(*simpleHTTPClient).Do
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:522 +0x1e3
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 8 [select]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).LookupIPAddr(0x27a0000, 0x1adfb40, 0xc420088420, 0xc42033f900, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/lookup.go:212 +0x50d
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).internetAddrList(0x27a0000, 0x1adfb40, 0xc420088420, 0x197861f, 0x3, 0xc42033f900, 0x17, 0x0, 0x0, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/ipsock.go:293 +0x5c4
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).resolveAddrList(0x27a0000, 0x1adfb40, 0xc420088420, 0x1978c7d, 0x4, 0x197861f, 0x3, 0xc42033f900, 0x17, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/dial.go:193 +0x50c
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Dialer).DialContext(0xc4202fbc80, 0x1adfb00, 0xc4200ac010, 0x197861f, 0x3, 0xc42033f900, 0x17, 0x0, 0x0, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/dial.go:375 +0x22b
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Dialer).Dial(0xc4202fbc80, 0x197861f, 0x3, 0xc42033f900, 0x17, 0x60, 0x110, 0x110, 0xc42036ed80)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/dial.go:320 +0x75
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Dialer).Dial-fm(0x197861f, 0x3, 0xc42033f900, 0x17, 0xc4200883c0, 0xc420069ae8, 0x4041c6, 0x61c829)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /go/src/github.com/coreos/flannel/vendor/github.com/coreos/etcd/client/client.go:52 +0x52
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net/http.(*Transport).dial(0xc4204ac000, 0x1adfb00, 0xc4200ac010, 0x197861f, 0x3, 0xc42033f900, 0x17, 0x5d, 0xffffffffffffffff, 0x0, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:901 +0x78
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net/http.(*Transport).dialConn(0xc4204ac000, 0x1adfb00, 0xc4200ac010, 0x0, 0xc4202382a0, 0x5, 0xc42033f900, 0x17, 0xc4204ac000, 0xc420148e00, ...)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:1143 +0x317
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net/http.(*Transport).getConn.func4(0xc4204ac000, 0x1adfb00, 0xc4200ac010, 0xc4203cf5c0, 0xc420092720)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:957 +0x78
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by net/http.(*Transport).getConn
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/http/transport.go:956 +0x363
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: goroutine 9 [select]:
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.cgoLookupIP(0x1adfac0, 0xc42022f080, 0xc42033f900, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/cgo_unix.go:212 +0x19f
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).lookupIP(0x27a0000, 0x1adfac0, 0xc42022f080, 0xc42033f900, 0x11, 0x0, 0xc4203c4600, 0xc4200b2040, 0x0, 0x17043c0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/lookup_unix.go:95 +0x12d
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).(net.lookupIP)-fm(0x1adfac0, 0xc42022f080, 0xc42033f900, 0x11, 0x429189, 0x8, 0xc4200b2040, 0x0, 0xc420058ea0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/lookup.go:192 +0x56
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.glob..func10(0x1adfac0, 0xc42022f080, 0xc4204534b0, 0xc42033f900, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/hook.go:19 +0x52
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/net/lookup.go:206 +0xd8
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: internal/singleflight.(*Group).doCall(0x279fff0, 0xc42014d040, 0xc42033f900, 0x11, 0xc4203cf710)
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]: created by internal/singleflight.(*Group).DoChan
May 02 18:10:33 ip-10-10-11-49 microk8s.daemon-flanneld[31518]:         /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2d0
May 02 18:10:33 ip-10-10-11-49 systemd[1]: snap.microk8s.daemon-flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 02 18:10:33 ip-10-10-11-49 systemd[1]: snap.microk8s.daemon-flanneld.service: Failed with result 'exit-code'.
```

if I use master ip address instead of its DNS address, flanneld starts successfully.

**Comment by ktsakalozos** [comment]
Hi @carlosrmendes. The default value we have is `--etcd-endpoints=https://127.0.0.1:12379`, see [1]. This default value is used on a single node cluster where etcd and flanneld run on the same host. 

When a worker node is added (with `microk8s add-node` and `microk8s join`) flanneld on the worker node needs to talk to etcd on the master so the `--etcd-endpoints` argument is updated with the IP of the master node, see [2].

How was the `master.example.internal` produced? Could you share the format of the connection point produced with `microk8s add-node`? When you `microk8s add-node` you should get a connections string looking like `192.168.24.140:25000/a9b367bbqmk2495f4aft1b797e3asdrb` is `master.example.internal` shown in the connection string instead of the IP of the master?

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/flanneld#L2 
[2] https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/join.py#L160

**Comment by carlosrmendes** [comment]
these issues seems related:
https://github.com/coreos/flannel/issues/1104
https://github.com/coreos/flannel/issues/977
