### ISSUE TITLE
Rebuilding snap always fails, must always do snapcraft clean folllowed by snapcraft --use-lxd

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#1223]
Lately, I've been experiencing failure when rebuilding the snap.

This is the error I am getting.

```
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                                                                                                        
Hit http://archive.ubuntu.com/ubuntu xenial InRelease                                                                                                                                                             
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                                                                                                                          
Get:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                                                                                                        
Fetched 325 kB in 0s (0 B/s)                                                                                                                                                                                      
Copying needed target link from the system /root/parts/microk8s/install/go/src/github.com/kubernetes/kubernetes/_output/local/bin/linux/amd64
[Errno 21] Is a directory: '/root/parts/microk8s/install/go/src/github.com/kubernetes/kubernetes/_output/local/bin/linux/amd64'
We would appreciate it if you anonymously reported this issue.
No other data than the traceback and the version of snapcraft in use will be sent.
Would you like to send this error data? (Yes/No/Always/View) [no]: view
Traceback (most recent call last):
  File "/snap/snapcraft/4282/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==3.9.1', 'console_scripts', 'snapcraft')()
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/cli/_command.py", line 88, in invoke
    return super().invoke(ctx)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 280, in snap
    _execute(steps.PRIME, parts=[], pack_project=True, output=output, **kwargs)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/cli/lifecycle.py", line 78, in _execute
    lifecycle.execute(step, project_config, parts)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 131, in execute
    executor.run(step, part_names)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 185, in run
    self._handle_step(part_names, part, step, current_step, cli_config)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 231, in _handle_step
    self._handle_outdated(part, current_step, outdated_report, cli_config)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 369, in _handle_outdated
    self._prepare_step(step=step, part=part)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/lifecycle/_runner.py", line 307, in _prepare_step
    preparation_function()
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 451, in prepare_pull
    self._unpack_stage_packages()
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/pluginhandler/__init__.py", line 445, in _unpack_stage_packages
    self._stage_packages_repo.unpack(self.plugin.installdir)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/repo/_deb.py", line 585, in unpack
    self.normalize(unpackdir)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 217, in normalize
    self._fix_artifacts(unpackdir)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 262, in _fix_artifacts
    self._fix_symlink(path, unpackdir, root)
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 295, in _fix_symlink
    if not os.path.exists(target) and not _try_copy_local(path, target):
  File "/snap/snapcraft/4282/lib/python3.6/site-packages/snapcraft/internal/repo/_base.py", line 317, in _try_copy_local
    shutil.copyfile(os.readlink(path), target)
  File "/snap/snapcraft/4282/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/root/parts/microk8s/install/go/src/github.com/kubernetes/kubernetes/_output/local/bin/linux/amd64'
We would appreciate it if you anonymously reported this issue.
No other data than the traceback and the version of snapcraft in use will be sent.
Would you like to send this error data? (Yes/No/Always/View) [no]: n
```
I have to do `snapcraft clean` followed by `snapcraft --use-lxd` before i can proceed.  Doing the clean makes it really slow when debugging / iterating through some changes. 

I don't see this happening before.  Any help will be greatly appreciated.

**Comment by balchua** [comment]
I can do the `snapcraft clean microk8s`, but if my changes does not require a rebuild of kubernetes binaries, is it possible to reuse them?  I couldn't find the previous documentation on how to reuse prebuilt binaries.

**Comment by balchua** [comment]
kindda found a way not to fail the build.
By doing an `rm -rf $GOPATH/src/$KUBERNETES_REPOSITORY/_output/` in the file `build-k8s-binaries.sh`.

This has **NO** effect on the build time, as snap detects that the source has changed and will proceed to perform the build.  But i feel that it is better than throwing that error out.

@ktsakalozos or anyone Wdyt?  

I can submit a PR for this.

**Comment by ktsakalozos** [comment]
@sergiusens any hints on ho we could address this issue?
