### ISSUE TITLE
`edge` channel issue when joining worker node

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#1224]
When using the `edge` channel, joining a worker node is failing.

This is due to the cluster agent not returning the right token back (it is returning `None`) to the client.

Further diggin, found out that `get_token()` method (in `agent.py`) is not iterating through the `known_tokens.csv` to find a match.

Thrown error when joining a node:

```shell
$ microk8s join 10.0.0.5:25000/qwertyuiopasdfghjklzxcvbnm123456
Traceback (most recent call last):
  File "/snap/microk8s/x2/scripts/cluster/join.py", line 737, in <module>
    join_etcd(connection_parts)
  File "/snap/microk8s/x2/scripts/cluster/join.py", line 699, in join_etcd
    update_kubeproxy(info["kubeproxy"], info["ca"], master_ip, info["apiport"], hostname_override)
  File "/snap/microk8s/x2/scripts/cluster/join.py", line 219, in update_kubeproxy
    create_kubeconfig(token, ca, master_ip, api_port, "proxy.config", "kubeproxy")
  File "/snap/microk8s/x2/scripts/cluster/join.py", line 202, in create_kubeconfig
    config_txt = config_txt.replace("TOKEN", token)
TypeError: Can't convert 'NoneType' object to str implicitly

```

**Comment by balchua** [comment]
closing this, resolved by the PR
