### ISSUE TITLE
[v1.19.2] HA Cluster scheduler and controller-manager fail on standby nodes; "microk8s status" fails or takes over 10 mins to run

### ISSUE THREAD

**Issue by alwynpan** [ubuntu/microk8s#1608]
# Version

**microk8s:** v1.19.2-34+1b3fa60b402c1c  

# Issues

microk8s was installed using snap channel `1.19/stable`, Rev `1710`.

## `scheduler` and `controller-manager` fail on standby nodes

Not sure if this is expected, but I noticed that some services fail on the standby nodes. Currently I have both `scheduler` and `controller-manger` fail, while I have seen `apiserver` and `scheduler` fail yesterday.

[inspection-report-20200929_153840.tar.gz](https://github.com/ubuntu/microk8s/files/5296680/inspection-report-20200929_153840.tar.gz)

```bash
ubuntu@rancher-server-node-4:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
 FAIL:  Service snap.microk8s.daemon-scheduler is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-scheduler
 FAIL:  Service snap.microk8s.daemon-controller-manager is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-controller-manager
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```

## `microk8s status` takes over 10 mins to complete on some of the nodes

I also noticed on some of the nodes, the `microk8s status` command can take over 10 mins to complete.

## `microk8s status` fail to run

On one of the nodes, the `microk8s status` command failed to run after around 2 - 5 mins. `microk8s inspect` shows everything is fine.

[inspection-report-20200929_153352.tar.gz](https://github.com/ubuntu/microk8s/files/5296719/inspection-report-20200929_153352.tar.gz)

```bash
ubuntu@rancher-server-node-3:~$ microk8s status
Traceback (most recent call last):
  File "/snap/microk8s/1710/scripts/wrappers/status.py", line 229, in <module>
    enabled, disabled = get_status(available_addons, isReady)
  File "/snap/microk8s/1710/scripts/wrappers/status.py", line 156, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/1710/scripts/wrappers/common/utils.py", line 149, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/1710/scripts/wrappers/common/utils.py", line 29, in run
    result.check_returncode()
  File "/snap/microk8s/1710/usr/lib/python3.5/subprocess.py", line 659, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/1710/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1
```

```bash
ubuntu@rancher-server-node-3:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```

**Comment by alwynpan** [comment]
Another one that I have noticed is the `datastore standby nodes` keeps shifting among the nodes (I have four nodes). Does that mean a random `master node` keeps failing?

**Comment by alwynpan** [comment]
6 hours after the cluster was created, one of the nodes is completely gone. No other workload was deployed to the cluster apart from a CEPH storage cluster (via rook). 

```bash
ubuntu@rancher-server-node-1:~$ k get node
NAME                    STATUS     ROLES    AGE     VERSION
rancher-server-node-2   Ready      <none>   6h22m   v1.19.2-34+1b3fa60b402c1c
rancher-server-node-1   Ready      <none>   8h      v1.19.2-34+1b3fa60b402c1c
rancher-server-node-4   Ready      <none>   6h15m   v1.19.2-34+1b3fa60b402c1c
rancher-server-node-3   NotReady   <none>   6h17m   v1.19.2-34+1b3fa60b402c1c
```

```bash
ubuntu@rancher-server-node-3:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```
[inspection-report-20200929_195159.tar.gz](https://github.com/ubuntu/microk8s/files/5298064/inspection-report-20200929_195159.tar.gz)

```bash
ubuntu@rancher-server-node-3:~$ sudo systemctl status snap.microk8s.daemon-apiserver
● snap.microk8s.daemon-apiserver.service - Service for snap application microk8s.daemon-apiserver
   Loaded: loaded (/etc/systemd/system/snap.microk8s.daemon-apiserver.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Tue 2020-09-29 18:07:37 AEST; 1h 49min ago
  Process: 16529 ExecStart=/usr/bin/snap run microk8s.daemon-apiserver (code=killed, signal=SEGV)
 Main PID: 16529 (code=killed, signal=SEGV)

Sep 29 18:07:36 rancher-server-node-3 systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'signal'.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: snap.microk8s.daemon-apiserver.service: Service hold-off time over, scheduling restart.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: snap.microk8s.daemon-apiserver.service: Scheduled restart job, restart counter is at 5.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: snap.microk8s.daemon-apiserver.service: Start request repeated too quickly.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'signal'.
Sep 29 18:07:37 rancher-server-node-3 systemd[1]: Failed to start Service for snap application microk8s.daemon-apiserver.
```

Restart the service did not fix the segmentation fault.

**Comment by balchua** [comment]
Hi @alwynpan thank you for reporting the issue.  It seems like you are experiencing the same issue reported here https://github.com/ubuntu/microk8s/issues/1598

If you can try `latest/edge` channel were some fixes are applied.  But you may have to `snap remove microk8s --purge` to get a clean cluster. 
Apologies for the inconvenience.

**Comment by ktsakalozos** [comment]
Hi @alwynpan 

> `scheduler` and `controller-manager` fail on standby nodes

It is expected that the `scheduler` and the `control-manager` to run only on the voter nodes not the standby ones. You are right we should not be reporting this as a "FAILURE".


> `microk8s status` takes over 10 mins to complete on some of the nodes

The `microk8s status` command checks that the apiserver is running and that there is at least one worker node ready. During this invocation the apiserver stopped working/restarted.

For recovering the failing node you may want to look at [1] and as mentioned above switch to `latest/edge`.

[1] https://discuss.kubernetes.io/t/recovery-of-ha-microk8s-clusters/12931/3

**Comment by alwynpan** [comment]
Hi @ktsakalozos @balchua,

Thank you so much for the prompt response. This cluster was for testing only. The production clusters are still running on 1.18. I made this deployment to test the HA cluster before upgrade the existing ones. I think it might be easier to teardown the VMs and start from scratch. In fact, I have done this a few times before I raised this ticket to make sure there were not user errors.

Just want to check when can we expect this issue to be fixed in the 1.19/stable channel? Also, I just feel a bit confused about the versioning in snap store:

```
channels:
  1.19/stable:      v1.19.2         2020-09-26 (1710) 214MB classic
  1.19/candidate:   v1.19.2         2020-09-22 (1710) 214MB classic
  1.19/beta:        v1.19.2         2020-09-22 (1710) 214MB classic
  1.19/edge:        v1.19.2         2020-09-28 (1732) 214MB classic
  latest/stable:    v1.19.0         2020-09-08 (1668) 214MB classic
  latest/candidate: v1.19.2         2020-09-24 (1723) 214MB classic
  latest/beta:      v1.19.2         2020-09-24 (1723) 214MB classic
  latest/edge:      v1.19.2         2020-09-28 (1731) 214MB classic
``` 
Shouldn't the `1.19/stable` and `latest/stable` point to the same rev?

**Comment by ktsakalozos** [comment]
@alwynpan, the revisions (ie 1710, 1668) on latest and 1.19 tracks do not match because they are different builds of the same source code. As soon as we merge a change on the master branch a build is triggered for latest/edge and a second build on 1.19/edge. For now 1.19 and latest both build from master, 1.19 will eventually build from its own branch. The */edge revisions are tested and promoted to the respective beta candidate and stable channels.

The version of k8s on latest/stable and 1.19/stable currently do not match (1.19.0 vs 1.19.2) because I paused the promotion process from candidate to stable until we address this issue. If you have a long lasting k8s installation you would better not follow the latest track.

**Comment by Berndserk** [comment]
> @alwynpan, the revisions (ie 1710, 1668) on latest and 1.19 tracks do not match because they are different builds of the same source code. As soon as we merge a change on the master branch a build is triggered for latest/edge and a second build on 1.19/edge. For now 1.19 and latest both build from master, 1.19 will eventually build from its own branch. The */edge revisions are tested and promoted to the respective beta candidate and stable channels.
> 
> The version of k8s on latest/stable and 1.19/stable currently do not match (1.19.0 vs 1.19.2) because I paused the promotion process from candidate to stable until we address this issue. If you have a long lasting k8s installation you would better not follow the latest track.

Can't we then revert 1.19/stable to 1.19.0, which somehow is more stable than 1.19.2... i had to take latest/stable beacause it is currently the ONLY version where a 7 node HA cluster is running. But I want to avoid an auto update to 1.20 afterwards :-(
