### ISSUE TITLE
v1.18.9 flanneld segfault on groovy

### ISSUE THREAD

**Issue by panlinux** [ubuntu/microk8s#1644]
```
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2972]: PrevNode.Value: {"Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2978]: {"Network": "10.1.0.0/16", "Backend": {"Type": "vxlan"}}
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: fatal error: unexpected signal during runtime execution
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f27a28a10c4]
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime stack:
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime.throw(0x19a3a14, 0x2a)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/panic.go:616 +0x81
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime.sigpanic()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/signal_unix.go:372 +0x28e
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: goroutine 1 [syscall, locked to thread]:
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime.cgocall(0x14432e0, 0xc420079c50, 0x19a184f)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420079c08 sp=0xc420079bd0 pc=0x402304
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user._Cfunc_mygetpwuid_r(0x0, 0xc4200a6d20, 0x3002460, 0x400, 0xc4200b0030, 0x0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011_cgo_gotypes.go:170 +0x4d fp=0xc420079c50 sp=0xc420079c08 pc=0x6c637d
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.lookupUnixUid.func1.1(0x0, 0xc4200a6d20, 0x3002460, 0x400, 0xc4200b0030, 0xc420079ce0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x13f fp=0xc420079c90 sp=0xc420079c50 pc=0x6c79ef
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.lookupUnixUid.func1(0xc420079cb0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/cgo_lookup_unix.go:100 +0x50 fp=0xc420079cd0 sp=0xc420079c90 pc=0x6c7a90
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.retryWithBuffer(0xc4200a2a50, 0xc420079dc0, 0xc4200a2a50, 0x0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/cgo_lookup_unix.go:253 +0x3b fp=0xc420079d30 sp=0xc420079cd0 pc=0x6c6ebb
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x130 fp=0xc420079df8 sp=0xc420079d30 pc=0x6c6800
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.current(0xc420079e60, 0x10, 0xc420079e58)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x27 fp=0xc420079e28 sp=0xc420079df8 pc=0x6c6697
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.Current.func1()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/lookup.go:11 +0x22 fp=0xc420079e50 sp=0xc420079e28 pc=0x6c7832
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: sync.(*Once).Do(0x27a14c0, 0x19f7218)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/sync/once.go:44 +0xbe fp=0xc420079e88 sp=0xc420079e50 pc=0x46c45e
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/user.Current(0xc4200ae410, 0xa, 0xc4200ae410)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/user/lookup.go:11 +0x3d fp=0xc420079eb8 sp=0xc420079e88 pc=0x6c5f5d
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: github.com/coreos/flannel/vendor/github.com/golang/glog.init.1()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog_file.go:63 +0x39 fp=0xc420079f10 sp=0xc420079eb8 pc=0x6cc4f9
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: github.com/coreos/flannel/vendor/github.com/golang/glog.init()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011<autogenerated>:1 +0x1c2 fp=0xc420079f58 sp=0xc420079f10 pc=0x6cd212
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: main.init()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011<autogenerated>:1 +0x87 fp=0xc420079f88 sp=0xc420079f58 pc=0x1441b87
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime.main()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/proc.go:186 +0x1ca fp=0xc420079fe0 sp=0xc420079f88 pc=0x42be9a
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: runtime.goexit()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420079fe8 sp=0xc420079fe0 pc=0x456f71
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: goroutine 19 [syscall]:
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/signal.signal_recv(0x0)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: os/signal.loop()
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: created by os/signal.init.0
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: goroutine 20 [chan receive]:
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x27a1f40)
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x8b
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
Oct 13 20:03:03 ubuntu microk8s.daemon-flanneld[2912]: #011/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203
```
[inspection-report-20201013_200635.tar.gz](https://github.com/ubuntu/microk8s/files/5373823/inspection-report-20201013_200635.tar.gz)

**Comment by panlinux** [comment]
I'm trying other versions, and so far only 1.19.x worked. 1.16 is segfaulting, 1.17 is failing to start (I couldn't catch the segfault, but flanneld is also restarting there, maybe the SIGSEV is being logged elsewhere).

**Comment by JosefWN** [comment]
Getting the same thing (also running on Groovy)... On v1.19.2 as well, unfortunately.
