### ISSUE TITLE
Unable to connect to the server: unexpected EOF

### ISSUE THREAD

**Issue by djjudas21** [ubuntu/microk8s#1770]
I have used microk8s for a while on a single node to host some production workloads. Today I needed to check logs in one of the pods and discovered that while most things seem to be working fine, the `logs` and `exec` actions fail. Other actions like `create` and `apply` work fine.

```
[jonathan@zeus ~]$ microk8s kubectl -n camerahub-preprod get pods
NAME                               READY   STATUS      RESTARTS   AGE
postgres-backup-1606100400-b9c7n   0/1     Completed   0          18h
postgres-backup-1606014000-dktmd   0/1     Completed   0          42h
postgres-backup-1605927600-5dp8f   0/1     Completed   0          2d18h
redis-cluster-0                    1/1     Running     4          4d10h
postgres-replica-0                 1/1     Running     4          4d10h
redis-cluster-1                    1/1     Running     4          4d10h
postgres-0                         1/1     Running     4          4d10h
camerahub-b5dbb7676-698x6          0/1     Running     7          4d
camerahub-6cfc8d9cd8-bbplj         0/1     Running     9          52m
```

```
[jonathan@zeus ~]$ microk8s kubectl -n camerahub-preprod logs camerahub-6cfc8d9cd8-bbplj
Unable to connect to the server: unexpected EOF
```

```
[jonathan@zeus ~]$ microk8s kubectl -n camerahub-preprod exec -it camerahub-6cfc8d9cd8-bbplj -- sh
W1123 21:29:56.949157  552486 http.go:424] Error reading backend response: unexpected EOF
                                                                                         error: error sending request: Post "https://127.0.0.1:16443/api/v1/namespaces/camerahub-preprod/pods/camerahub-6cfc8d9cd8-bbplj/exec?command=sh&container=camerahub&stdin=true&stdout=true&tty=true": unexpected EOF
```

I haven't found much on Google about this error. I have tried stopping and starting microk8s and rebooting the server, which did not help. I have **not** yet attempted to run`microk8s reset` as I am cautious about some of my production PVs - I assume they can be remounted but I'm not 100% sure how that works yet.

[inspection-report-20201123_213231.tar.gz](https://github.com/ubuntu/microk8s/files/5585882/inspection-report-20201123_213231.tar.gz)

**Comment by balchua** [comment]
@djjudas21 are you behind a proxy?  If yes you may want to follow these [instructions](https://microk8s.io/docs/install-proxy)

**Comment by ktsakalozos** [comment]
Hi @djjudas21 

You would better not do a `microk8s reset` as reset will reduce the cluster to a single node empty cluster.

Since this is a production system you would better not use the latest stable channel. Instead you would want to follow a specific release track so you do get patch updates but your cluster will not be updated to the latest upstream stable without a warning when that gets released. Try deploying with `sudo snap install microk8s --classic --channel=1.19/stable`

In the attached logs I see the api server not so healthy, there is this error: 
```
Nov 23 21:29:35 zeus.jg.lan microk8s.daemon-apiserver[541137]: /snap/microk8s/1786/kube-apiserver: symbol lookup error: /snap/core/current/lib/x86_64-linux-gnu/libnss_dns.so.2: undefined symbol: __res_maybe_init, version GLIBC_PRIVATE
```    

What distribution are you on?

**Comment by djjudas21** [comment]
Hi @ktsakalozos and @balchua. Thanks for the advice - I'll pin to a stable release. I'm running Fedora 33 - I upgraded to it a few weeks ago. api server was working fine on Fedora 32 so I guess it broke with the upgrade. I haven't needed to run `logs` or `exec` actions since I upgraded.

**Comment by djjudas21** [comment]
Well, I ran this to pin the version. It did actually do a minor update from 1786 to 1791, but the problem with the api server is still there
```
[jonathan@zeus ~]$ snap list
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.47.1  10185  latest/stable  canonical✓  core
microk8s  v1.19.3    1786   latest/stable  canonical✓  classic

[jonathan@zeus ~]$ sudo snap refresh microk8s --classic --channel=1.19/stable
microk8s (1.19/stable) v1.19.3 from Canonical✓ refreshed

[jonathan@zeus ~]$ snap list
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.47.1  10185  latest/stable  canonical✓  core
microk8s  v1.19.3    1791   1.19/stable    canonical✓  classic
```

**Comment by djjudas21** [comment]
Just to follow up on this, I created a set of new Fedora 33 VMs and installed microk8s, and none of them showed this problem. I added them to a cluster with the (physical) node that *does* have the problem, and migrated all my workloads. I then wiped and reinstalled the physical node with Fedora 33, identical setup to the VMs - and it does have the problem again! So I am very confused.

These are the steps I went through to provision the new nodes:
```
# Brand new Fedora 33 install
[jonathan@zeus ~]$ sudo dnf install libcgroup libcgroup-tools 
[jonathan@zeus ~]$ sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
[jonathan@zeus ~]$ sudo init 6

[jonathan@zeus ~]$ sudo dnf -y install snapd
[jonathan@zeus ~]$ sudo systemctl enable --now snapd
[jonathan@zeus ~]$ sudo ln -s /var/lib/snapd/snap /snap
[jonathan@zeus ~]$ sudo snap install microk8s --classic --channel=1.20/stable
[jonathan@zeus ~]$ sudo usermod -a -G microk8s jonathan
[jonathan@zeus ~]$ sudo chown -f -R jonathan ~/.kube
[jonathan@zeus ~]$ microk8s start
[jonathan@zeus ~]$ exit

# For debugging, disable firewall and SELinux
[jonathan@zeus ~]$ sudo systemctl stop firewalld
[jonathan@zeus ~]$ sudo setenforce 0

# Testing
[jonathan@zeus ~]$ microk8s kubectl get no
NAME          STATUS   ROLES    AGE     VERSION
zeus.jg.lan   Ready    <none>   4m49s   v1.20.0-37+7ab055a22f5440

[jonathan@zeus ~]$ kubectl get po --all-namespaces
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-node-77pzt                         1/1     Running   1          4m56s
kube-system   calico-kube-controllers-847c8c99d-jc76w   1/1     Running   0          5m3s
[jonathan@zeus ~]$ microk8s kubectl exec -it -n kube-system calico-kube-controllers-847c8c99d-jc76w -- sh
W1230 12:01:12.203712    5567 http.go:473] Error reading backend response: unexpected EOF
                                                                                         error: error sending request: Post "https://127.0.0.1:16443/api/v1/namespaces/kube-system/pods/calico-kube-controllers-847c8c99d-jc76w/exec?command=sh&container=calico-kube-controllers&stdin=true&stdout=true&tty=true": unexpected EOF

[jonathan@zeus ~]$ microk8s kubectl logs -n kube-system calico-kube-controllers-847c8c99d-jc76w
Unable to connect to the server: unexpected EOF
```
New inspection report:
[inspection-report-20201230_140216.tar.gz](https://github.com/ubuntu/microk8s/files/5754442/inspection-report-20201230_140216.tar.gz)

**Comment by djjudas21** [comment]
Continuing my investigation. These are the nodes I currently have - `zeus.jg.lan` is a physical system and `zeus-kubeXX` are VirtualBox VMs hosted elsewhere. All built identically with the process I described in https://github.com/ubuntu/microk8s/issues/1770#issuecomment-752633318

```
[jonathan@zeus ~]$ microk8s kubectl get no -o wide
NAME          STATUS   ROLES    AGE     VERSION                     INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                     KERNEL-VERSION           CONTAINER-RUNTIME
zeus-kube02   Ready    <none>   8d      v1.20.0-37+7ab055a22f5440   192.168.0.44   <none>        Fedora 33 (Server Edition)   5.9.13-200.fc33.x86_64   containerd://1.3.7
zeus-kube03   Ready    <none>   8d      v1.20.0-37+7ab055a22f5440   192.168.0.45   <none>        Fedora 33 (Server Edition)   5.9.13-200.fc33.x86_64   containerd://1.3.7
zeus.jg.lan   Ready    <none>   4d12h   v1.20.0-37+7ab055a22f5440   192.168.0.2    <none>        Fedora 33 (Server Edition)   5.9.16-200.fc33.x86_64   containerd://1.3.7
```

So let's find a set of pods running across my nodes - MetalLB speakers seem a good bet:

```
[jonathan@zeus ~]$ microk8s kubectl get po -n metallb-system -o wide
NAME                          READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
speaker-nwd44                 1/1     Running   8          8d      192.168.0.45   zeus-kube03   <none>           <none>
speaker-9xrcw                 1/1     Running   0          4d12h   192.168.0.2    zeus.jg.lan   <none>           <none>
speaker-kssxw                 1/1     Running   2          8d      192.168.0.44   zeus-kube02   <none>           <none>
controller-559b68bfd8-299wf   1/1     Running   2          7d10h   10.1.152.153   zeus-kube02   <none>           <none>
```

Running `kubectl` commands on `zeus`, it can't get logs for pods running on itself:

```
[jonathan@zeus ~]$ microk8s kubectl logs -n metallb-system speaker-9xrcw
Unable to connect to the server: unexpected EOF
```

Nor can `zeus` get logs for pods running on another node, in this case `zeus-kube02`

```
[jonathan@zeus ~]$ microk8s kubectl logs -n metallb-system speaker-kssxw
Unable to connect to the server: unexpected EOF
```

However, both of these commands *succeed* when run on `zeus-kube02` against pods on `zeus` and `zeus-kube02`

```
[jonathan@zeus-kube02 ~]$ microk8s kubectl logs -n metallb-system speaker-9xrcw
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.0.44:7946","ts":"2021-01-06T13:43:40.036316999Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.0.44:59532","ts":"2021-01-06T13:43:43.485950126Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.0.44:7946","ts":"2021-01-06T13:44:10.038177723Z"}
...


[jonathan@zeus-kube02 ~]$ microk8s kubectl logs -n metallb-system speaker-kssxw
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.0.45:59208","ts":"2021-01-04T07:06:28.668259121Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.0.2:7946","ts":"2021-01-04T07:06:49.271462973Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.0.2:60950","ts":"2021-01-04T07:07:19.139916875Z"}
...
```

* I have taken special care to always use `microk8s kubectl`, but the same problem occurs with other `kubectl` distributions, e.g. from homebrew or RPM packages.
* SELinux is Permissive and firewalld is stopped on all nodes for debugging.
* I have removed the `~/.kube` directory on `zeus` in case it had something bad in it, but this didn't help.
* `zeus` had homebrew on it for other packages, but I removed this in case it was adding a conflict. This didn't help

I tried running with full debug for more info. On zeus there is clearly a problem with the api server:

```
[jonathan@zeus ~]$ microk8s kubectl logs -n metallb-system speaker-kssxw -v=8
I0107 11:31:34.799408  455534 loader.go:379] Config loaded from file:  /var/snap/microk8s/1864/credentials/client.config
I0107 11:31:34.810178  455534 round_trippers.go:422] GET https://127.0.0.1:16443/api/v1/namespaces/metallb-system/pods/speaker-kssxw
I0107 11:31:34.810209  455534 round_trippers.go:429] Request Headers:
I0107 11:31:34.810224  455534 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/7ab055a
I0107 11:31:34.810238  455534 round_trippers.go:433]     Authorization: Bearer <masked>
I0107 11:31:34.810249  455534 round_trippers.go:433]     Accept: application/json, */*
I0107 11:31:35.912302  455534 round_trippers.go:448] Response Status: 200 OK in 1102 milliseconds
I0107 11:31:35.912334  455534 round_trippers.go:451] Response Headers:
I0107 11:31:35.912349  455534 round_trippers.go:454]     Content-Type: application/json
I0107 11:31:35.912362  455534 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: 062a3148-c688-4222-b006-02d60cb4f50d
I0107 11:31:35.912371  455534 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: 5a9812d7-0f19-4d96-8407-ca432f977548
I0107 11:31:35.912381  455534 round_trippers.go:454]     Date: Thu, 07 Jan 2021 11:31:35 GMT
I0107 11:31:35.912389  455534 round_trippers.go:454]     Cache-Control: no-cache, private
I0107 11:31:35.912691  455534 request.go:1107] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"speaker-kssxw","generateName":"speaker-","namespace":"metallb-system","selfLink":"/api/v1/namespaces/metallb-system/pods/speaker-kssxw","uid":"32205e77-3cfe-41e8-9c6c-23e6300b0c86","resourceVersion":"15704908","creationTimestamp":"2020-12-29T11:30:07Z","labels":{"app":"metallb","component":"speaker","controller-revision-hash":"5ffcb8558b","pod-template-generation":"1"},"annotations":{"prometheus.io/port":"7472","prometheus.io/scrape":"true"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"DaemonSet","name":"speaker","uid":"bb895e3e-67b0-4449-90ff-a0a56f41cb03","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2021-01-05T16:48:07Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:prometheus.io/port":{},"f:prometheus.io/scrape":{}},"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:component":{},"f:controller-revision-hash":{},"f:po [truncated 6493 chars]
I0107 11:31:35.924505  455534 round_trippers.go:422] GET https://127.0.0.1:16443/api/v1/namespaces/metallb-system/pods/speaker-kssxw/log
I0107 11:31:35.924536  455534 round_trippers.go:429] Request Headers:
I0107 11:31:35.924550  455534 round_trippers.go:433]     Authorization: Bearer <masked>
I0107 11:31:35.924560  455534 round_trippers.go:433]     Accept: application/json, */*
I0107 11:31:35.924569  455534 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/7ab055a
I0107 11:31:36.079148  455534 round_trippers.go:448] Response Status:  in 154 milliseconds
I0107 11:31:36.079179  455534 round_trippers.go:451] Response Headers:
I0107 11:31:36.079236  455534 helpers.go:234] Connection error: Get https://127.0.0.1:16443/api/v1/namespaces/metallb-system/pods/speaker-kssxw/log: unexpected EOF
F0107 11:31:36.079261  455534 helpers.go:115] Unable to connect to the server: unexpected EOF
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc0006fa000, 0x5e, 0xd3)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2a7b040, 0xc000000003, 0x0, 0x0, 0xc0002acf50, 0x284f51a, 0xa, 0x73, 0x40e200)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2a7b040, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc000a34b90, 0x1, 0x1)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1488
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000a4c090, 0x2f, 0x1)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x26e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1ced9e0, 0xc000a37fb0, 0x1bb70f8)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs.NewCmdLogs.func1(0xc00062eb00, 0xc0000c1240, 0x1, 0x4)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go:154 +0x1a5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00062eb00, 0xc0000c1200, 0x4, 0x4, 0xc00062eb00, 0xc0000c1200)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00055c840, 0xc00003a240, 0xc00003a1e0, 0x6)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a7b040)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 8 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec140, 0xc000430000, 0x1, 0xc00004aba0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc00004aba0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc00004aba0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
```

On `zeus-kube02`, the `logs` call is obviously successful and there's a huge amount of debug output, but the initial GET looks different and I don't know why.

```
[jonathan@zeus-kube02 ~]$ microk8s kubectl logs -n metallb-system speaker-kssxw -v=8
I0107 11:32:16.087305 3938269 loader.go:379] Config loaded from file:  /var/snap/microk8s/1864/credentials/client.config
I0107 11:32:16.088255 3938269 round_trippers.go:422] GET https://127.0.0.1:16443/api?timeout=32s
I0107 11:32:16.088269 3938269 round_trippers.go:429] Request Headers:
I0107 11:32:16.088279 3938269 round_trippers.go:433]     Accept: application/json, */*
I0107 11:32:16.088287 3938269 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/7ab055a
I0107 11:32:16.088297 3938269 round_trippers.go:433]     Authorization: Bearer <masked>
I0107 11:32:16.096490 3938269 round_trippers.go:448] Response Status: 200 OK in 8 milliseconds
I0107 11:32:16.096544 3938269 round_trippers.go:451] Response Headers:
I0107 11:32:16.096560 3938269 round_trippers.go:454]     Cache-Control: no-cache, private
I0107 11:32:16.096569 3938269 round_trippers.go:454]     Content-Type: application/json
I0107 11:32:16.096584 3938269 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: 062a3148-c688-4222-b006-02d60cb4f50d
I0107 11:32:16.096596 3938269 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: 5a9812d7-0f19-4d96-8407-ca432f977548
I0107 11:32:16.096604 3938269 round_trippers.go:454]     Content-Length: 136
I0107 11:32:16.096612 3938269 round_trippers.go:454]     Date: Thu, 07 Jan 2021 11:32:16 GMT
I0107 11:32:16.101810 3938269 request.go:1107] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"192.168.0.44:16443"}]}
I0107 11:32:16.106232 3938269 round_trippers.go:422] GET https://127.0.0.1:16443/apis?timeout=32s
I0107 11:32:16.106274 3938269 round_trippers.go:429] Request Headers:
I0107 11:32:16.106318 3938269 round_trippers.go:433]     Accept: application/json, */*
I0107 11:32:16.106358 3938269 round_trippers.go:433]     User-Agent: kubectl/v1.20.0 (linux/amd64) kubernetes/7ab055a
I0107 11:32:16.106403 3938269 round_trippers.go:433]     Authorization: Bearer <masked>
I0107 11:32:16.107950 3938269 round_trippers.go:448] Response Status: 200 OK in 1 milliseconds
I0107 11:32:16.107984 3938269 round_trippers.go:451] Response Headers:
I0107 11:32:16.107993 3938269 round_trippers.go:454]     Cache-Control: no-cache, private
I0107 11:32:16.108000 3938269 round_trippers.go:454]     Content-Type: application/json
I0107 11:32:16.108018 3938269 round_trippers.go:454]     X-Kubernetes-Pf-Flowschema-Uid: 062a3148-c688-4222-b006-02d60cb4f50d
I0107 11:32:16.108039 3938269 round_trippers.go:454]     X-Kubernetes-Pf-Prioritylevel-Uid: 5a9812d7-0f19-4d96-8407-ca432f977548
I0107 11:32:16.108053 3938269 round_trippers.go:454]     Date: Thu, 07 Jan 2021 11:32:16 GMT
I0107 11:32:16.112211 3938269 request.go:1107] Response Body: {"kind":"APIGroupList","apiVersion":"v1","groups":[{"name":"apiregistration.k8s.io","versions":[{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"},{"groupVersion":"apiregistration.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"apiregistration.k8s.io/v1","version":"v1"}},{"name":"apps","versions":[{"groupVersion":"apps/v1","version":"v1"}],"preferredVersion":{"groupVersion":"apps/v1","version":"v1"}},{"name":"events.k8s.io","versions":[{"groupVersion":"events.k8s.io/v1","version":"v1"},{"groupVersion":"events.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"events.k8s.io/v1","version":"v1"}},{"name":"authentication.k8s.io","versions":[{"groupVersion":"authentication.k8s.io/v1","version":"v1"},{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"authentication.k8s.io/v1","version":"v1"}},{"name":"authorization.k8s.io","versions":[{"groupVersion":"authorization.k8s.io/v1","version":"v1"},{"groupVersi [truncated 4634 chars]
```

Does anyone know what this all means? Thanks.

**Comment by balchua** [comment]
Hi @djjudas21 is `zeus.jg.lan` the same as `zeus`?
I was just wondering if that matters.  The apiserver seems to be fine.  As `kubectl get no` is returning the correct response.
`kubectl log` maybe also `kubectl exec` isn't working.
What is the output when u do `hostname` ?

**Comment by djjudas21** [comment]
Hi @balchua . Yes `zeus.jg.lan` is the same as `zeus`. `zeus.jg.lan` is the FQDN but I have DNS set up so everything resolves.

```
[jonathan@zeus ~]$ hostname
zeus.jg.lan

[jonathan@zeus ~]$ host zeus
zeus.jg.lan has address 192.168.0.2
```

**Comment by balchua** [comment]
Is there by any chance you can disable ipv6?  Im purely guessing here.  

Another thing to try.  `microk8s config` will get you the kubeconfig but using the non loopback interface.  Use that as your `KUBECONFIG` and try with the standalone `kubectl` binary.

**Comment by djjudas21** [comment]
IPv6 is a good shout, I will try disabling that. It is enabled the same on all of my nodes though, and it works on the others.

I have already tried regenerating the kubeconfig with `microk8s config` and behaviour is the same with the standalone `kubectl` client. I also tried using a `kubectl` client on a different machine, not part of the cluster. Queries sent to `zeus-kubeXX` were fine, but queries sent to `zeus` were not, identical behaviour to running `kubectl` locally on the nodes.

**Comment by balchua** [comment]
Do you still see this error in the apiserver logs?

```
Dec 30 14:00:53 zeus.jg.lan microk8s.daemon-apiserver[132378]: /snap/microk8s/1864/kube-apiserver: symbol lookup error: /snap/core/current/lib/x86_64-linux-gnu/libnss_dns.so.2: undefined symbol: __res_maybe_init, version GLIBC_PRIVATE
```
I got this from your previous inspect tarball https://github.com/ubuntu/microk8s/issues/1770#issuecomment-752633318

**Comment by djjudas21** [comment]
Yes, that error still occurs on `zeus` each time I run `microk8s kubectl logs ...`. It does **not** appear for those commands on `zeus-kube02`.

There is actually a difference between `zeus` and `zeus-kube02`, that `zeus` is running a `dnsmasq` instance to provide DNS+DHCP for my LAN. It's running as a bare-metal systemd unit, bound to the node's IP. I can't see how it would cause a problem, but maybe it is...? It is my intention to move dnsmasq off `zeus` in the near future to make the MicroK8s nodes truly ephemeral, so it will be interesting to see if that fixes this problem.

Interestingly `zeus-kubeXX` are apparently running an some embedded DNS cache inside NetworkManager, the way Fedora ships it, and that doesn't cause a problem.

I have no idea how the internals of the api-server work but does this give a lead to investigate? Happy to debug any way I can.

**Comment by balchua** [comment]
Could it be that when installing dnsmasq, it brought in libraries that is not compatible?
The library mentioned in the log seems to point to a dns library.
`/snap/core/current/lib/x86_64-linux-gnu/libnss_dns.so.2`.
I am just totally guessing here.

**Comment by djjudas21** [comment]
I don't think that's it, as the whole point of snaps is that they bring their own dependencies which are kept separate from system ones.

All I can think is that it's some weird behaviour about running a DNS resolver for the LAN on the same system that is also running Kubernetes internal DNS resolver. My Raspberry Pi should arrive today so I'll move my dnsmasq instance onto that and then all the MicroK8s node will be truly identical and have no "extra" services shoehorned in.

**Comment by djjudas21** [comment]
Just to update on this - I wiped and reinstalled `zeus`, set up `dnsmasq` again in the normal way with a static IP and providing DHCP+DHCP to the rest of the LAN, and then installed MicroK8s but did **not** yet join it to a cluster. Straight away it was showing this error with `kubectl logs`. I joined it to my cluster, and of course the error persisted.

So I set up `dnsmasq` on a Raspberry Pi and then rebuilt `zeus` without `dnsmasq`, using DHCP to get an IP. This time MicroK8s worked in standalone mode, and continued to work in clustered mode. So it looks like the presence of `dnsmasq` on the system somehow interferes with `libnss_dns.so.2`.

I'm happy to accept that this problem is mostly due to my environment - however if there is something wrong with DNS resolution then I would expect the error message to say it was unable to look something up, rather than crashing with a library error. So maybe there's an underlying bug that is being exposed by my environment? Or maybe an opportunity for a documentation improvement to warn about interactions  with `dnsmasq`?

I am no longer seeing this problem now I've moved `dnsmasq` away from MicroK8s but I am still happy to help track this down if it is useful to the MicroK8s project. Thanks for the help so far :+1:

**Comment by balchua** [comment]
@djjudas21 thanks for giving an update on this. 👍

**Comment by djjudas21** [comment]
I'm gonna close this because I don't think there is any further action to be taken but feel free to reopen and tag me if you want any further info :slightly_smiling_face:

**Comment by mattiasarro** [comment]
For what it's worth, in my case this was caused by proxy settings. `kubectl logs` fetches logs from kubelet at `hostname:10250`, and my proxy configuration was such that `hostname:10250` went to the proxy rather than `localhost:10250`. Adding hostname to `no_proxy` env var (in `/etc/environment`) and restarting microk8s did the trick.
