### ISSUE TITLE
microk8s kubectl logs returns forbidden

### ISSUE THREAD

**Issue by dirkm** [ubuntu/microk8s#1772]
I am on ubuntu 20.10 with microk8s v1.19.3 installed through snap.

I did a basic setup using the tutorial https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#2-deploying-microk8s

Everything seems to work as expected apart from getting the logs

```
dirk@tux0058:~$ microk8s kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
microbot-5f5499d479-dkdm6   1/1     Running   4          97m
microbot-5f5499d479-5hxzn   1/1     Running   4          97m
dirk@tux0058:~$ microk8s kubectl logs microbot-5f5499d479-dkdm6
Error from server: Get "https://tux0058:10250/containerLogs/default/microbot-5f5499d479-dkdm6/microbot": Forbidden
```

Running with verbosity on seems to hint to a parsing problem in a rest request

``` 
dirk@tux0058:~$ microk8s kubectl logs microbot-5f5499d479-dkdm6 -v=9
I1124 11:29:33.412559 3038714 loader.go:375] Config loaded from file:  /var/snap/microk8s/1786/credentials/client.config
I1124 11:29:33.413482 3038714 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.3 (linux/amd64) kubernetes/9e8b653" -H "Authorization: Bearer eitIbjc1WWVDa1NPUWdUeGwzNTF6RnZQa1M5T0N5eW90MS8wYUtYOHR4Yz0K" 'https://127.0.0.1:16443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I1124 11:29:33.418648 3038714 round_trippers.go:443] GET https://127.0.0.1:16443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 5 milliseconds
I1124 11:29:33.418663 3038714 round_trippers.go:449] Response Headers:
I1124 11:29:33.418668 3038714 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I1124 11:29:33.418673 3038714 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1124 11:29:33.418677 3038714 round_trippers.go:452]     Content-Length: 20
I1124 11:29:33.418681 3038714 round_trippers.go:452]     Date: Tue, 24 Nov 2020 10:29:33 GMT
I1124 11:29:33.418685 3038714 round_trippers.go:452]     Cache-Control: no-cache, private
I1124 11:29:33.426516 3038714 request.go:1097] Response Body: service unavailable
I1124 11:29:33.435120 3038714 request.go:1301] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1124 11:29:33.435137 3038714 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I1124 11:29:33.435166 3038714 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I1124 11:29:33.435416 3038714 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.3 (linux/amd64) kubernetes/9e8b653" -H "Authorization: Bearer eitIbjc1WWVDa1NPUWdUeGwzNTF6RnZQa1M5T0N5eW90MS8wYUtYOHR4Yz0K" 'https://127.0.0.1:16443/apis/metrics.k8s.io/v1beta1?timeout=32s'
I1124 11:29:33.436084 3038714 round_trippers.go:443] GET https://127.0.0.1:16443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 0 milliseconds
I1124 11:29:33.436097 3038714 round_trippers.go:449] Response Headers:
I1124 11:29:33.436102 3038714 round_trippers.go:452]     Cache-Control: no-cache, private
I1124 11:29:33.436106 3038714 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
I1124 11:29:33.436110 3038714 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1124 11:29:33.436113 3038714 round_trippers.go:452]     Content-Length: 20
I1124 11:29:33.436117 3038714 round_trippers.go:452]     Date: Tue, 24 Nov 2020 10:29:33 GMT
I1124 11:29:33.443760 3038714 request.go:1097] Response Body: service unavailable
I1124 11:29:33.452585 3038714 request.go:1301] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1124 11:29:33.452601 3038714 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I1124 11:29:33.453500 3038714 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.3 (linux/amd64) kubernetes/9e8b653" -H "Authorization: Bearer eitIbjc1WWVDa1NPUWdUeGwzNTF6RnZQa1M5T0N5eW90MS8wYUtYOHR4Yz0K" 'https://127.0.0.1:16443/api/v1/namespaces/default/pods/microbot-5f5499d479-dkdm6'
I1124 11:29:33.455773 3038714 round_trippers.go:443] GET https://127.0.0.1:16443/api/v1/namespaces/default/pods/microbot-5f5499d479-dkdm6 200 OK in 2 milliseconds
I1124 11:29:33.455786 3038714 round_trippers.go:449] Response Headers:
I1124 11:29:33.455797 3038714 round_trippers.go:452]     Cache-Control: no-cache, private
I1124 11:29:33.455809 3038714 round_trippers.go:452]     Content-Type: application/json
I1124 11:29:33.455817 3038714 round_trippers.go:452]     Date: Tue, 24 Nov 2020 10:29:33 GMT
I1124 11:29:33.455898 3038714 request.go:1097] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"microbot-5f5499d479-dkdm6","generateName":"microbot-5f5499d479-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/microbot-5f5499d479-dkdm6","uid":"efb095eb-f23a-4f31-af67-9672b40ac132","resourceVersion":"11881","creationTimestamp":"2020-11-24T08:49:13Z","labels":{"app":"microbot","pod-template-hash":"5f5499d479"},"annotations":{"cni.projectcalico.org/podIP":"10.1.93.100/32","cni.projectcalico.org/podIPs":"10.1.93.100/32"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"microbot-5f5499d479","uid":"fcb80296-c4ce-47f2-b53e-1e7208de275e","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-11-24T09:54:58Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"fcb80296-c4ce-47f2-b53e-1e7208de275e\"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid":{}}}},"f:spec":{"f:containers":{"k:{\"name\":\"microbot\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}},{"manager":"calico","operation":"Update","apiVersion":"v1","time":"2020-11-24T09:55:40Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:cni.projectcalico.org/podIP":{},"f:cni.projectcalico.org/podIPs":{}}}}},{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2020-11-24T09:55:43Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{"k:{\"type\":\"ContainersReady\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Initialized\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Ready\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:status":{},"f:type":{}}},"f:containerStatuses":{},"f:hostIP":{},"f:phase":{},"f:podIP":{},"f:podIPs":{".":{},"k:{\"ip\":\"10.1.93.100\"}":{".":{},"f:ip":{}}},"f:startTime":{}}}}]},"spec":{"volumes":[{"name":"default-token-cxcpm","secret":{"secretName":"default-token-cxcpm","defaultMode":420}}],"containers":[{"name":"microbot","image":"dontrebootme/microbot:v1","resources":{},"volumeMounts":[{"name":"default-token-cxcpm","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"tux0058","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"priority":0,"enableServiceLinks":true,"preemptionPolicy":"PreemptLowerPriority"},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-24T08:49:13Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-24T09:55:40Z"},{"type":"ContainersReady","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-24T09:55:40Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2020-11-24T08:49:13Z"}],"hostIP":"10.1.195.58","podIP":"10.1.93.100","podIPs":[{"ip":"10.1.93.100"}],"startTime":"2020-11-24T08:49:13Z","containerStatuses":[{"name":"microbot","state":{"running":{"startedAt":"2020-11-24T09:55:40Z"}},"lastState":{"terminated":{"exitCode":255,"reason":"Unknown","startedAt":"2020-11-24T09:28:45Z","finishedAt":"2020-11-24T09:54:33Z","containerID":"containerd://762ce6166d3335d4d73a4e7f0478c1223c5e02f3a38a01041a2674ef37dbe96a"}},"ready":true,"restartCount":4,"image":"docker.io/dontrebootme/microbot:v1","imageID":"sha256:899ceb044bf694340a22d71a28f4fff64c8197cee2ed7badde83e0032118970a","containerID":"containerd://96bc59a9f7b63a857c235cbcb1d41638108697e343a240f268934fa82119e763","started":true}],"qosClass":"BestEffort"}}
I1124 11:29:33.461504 3038714 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.3 (linux/amd64) kubernetes/9e8b653" -H "Authorization: Bearer eitIbjc1WWVDa1NPUWdUeGwzNTF6RnZQa1M5T0N5eW90MS8wYUtYOHR4Yz0K" 'https://127.0.0.1:16443/api/v1/namespaces/default/pods/microbot-5f5499d479-dkdm6/log'
I1124 11:29:33.467454 3038714 round_trippers.go:443] GET https://127.0.0.1:16443/api/v1/namespaces/default/pods/microbot-5f5499d479-dkdm6/log 500 Internal Server Error in 5 milliseconds
I1124 11:29:33.467474 3038714 round_trippers.go:449] Response Headers:
I1124 11:29:33.467481 3038714 round_trippers.go:452]     Content-Length: 190
I1124 11:29:33.467487 3038714 round_trippers.go:452]     Date: Tue, 24 Nov 2020 10:29:33 GMT
I1124 11:29:33.467491 3038714 round_trippers.go:452]     Cache-Control: no-cache, private
I1124 11:29:33.467496 3038714 round_trippers.go:452]     Content-Type: application/json
I1124 11:29:33.467512 3038714 request.go:1097] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get \"https://tux0058:10250/containerLogs/default/microbot-5f5499d479-dkdm6/microbot\": Forbidden","code":500}
I1124 11:29:33.467836 3038714 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get \"https://tux0058:10250/containerLogs/default/microbot-5f5499d479-dkdm6/microbot\": Forbidden",
  "code": 500
}]
F1124 11:29:33.467852 3038714 helpers.go:115] Error from server: Get "https://tux0058:10250/containerLogs/default/microbot-5f5499d479-dkdm6/microbot": Forbidden
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc000220120, 0xa1, 0x104)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2d14b40, 0xc000000003, 0x0, 0x0, 0xc00084aee0, 0x2ae84ec, 0xa, 0x73, 0x40b300)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2d14b40, 0x3, 0x0, 0x0, 0x2, 0xc00055d780, 0x1, 0x1)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1442
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc0004e8580, 0x72, 0x1)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x1f0
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1e5b0e0, 0xc0009cbf40, 0x1d06c98)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs.NewCmdLogs.func1(0xc000846000, 0xc000327e00, 0x1, 0x2)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go:154 +0x1a5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000846000, 0xc000327de0, 0x2, 0x2, 0xc000846000, 0xc000327de0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a78c0, 0xc00008a180, 0xc00003a0c0, 0x4)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2d14b40)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 37 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1d06bd0, 0x1e5b3e0, 0xc00040e030, 0x1, 0xc000040240)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1d06bd0, 0x12a05f200, 0x0, 0x1, 0xc000040240)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1d06bd0, 0x12a05f200, 0xc000040240)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

goroutine 98 [IO wait]:
internal/poll.runtime_pollWait(0x7fe219f4f398, 0x72, 0x1e5e5c0)
	/snap/go/6633/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0009fa998, 0x72, 0x1e5e500, 0x2b1f610, 0x0)
	/snap/go/6633/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/6633/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0009fa980, 0xc0003ce000, 0x1d61, 0x1d61, 0x0, 0x0, 0x0)
	/snap/go/6633/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0009fa980, 0xc0003ce000, 0x1d61, 0x1d61, 0x203000, 0x6529bb, 0xc000b36160)
	/snap/go/6633/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0003d6078, 0xc0003ce000, 0x1d61, 0x1d61, 0x0, 0x0, 0x0)
	/snap/go/6633/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000a200e0, 0xc0003ce000, 0x1d61, 0x1d61, 0xd8, 0x1d5c, 0xc000a15710)
	/snap/go/6633/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000b36280, 0x1e59de0, 0xc000a200e0, 0x40b645, 0x1a19320, 0x1b95580)
	/snap/go/6633/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000b36000, 0x1e5c920, 0xc0003d6078, 0x5, 0xc0003d6078, 0xc7)
	/snap/go/6633/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000b36000, 0x0, 0x0, 0xc000a15d18)
	/snap/go/6633/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/snap/go/6633/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000b36000, 0xc0009ee000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/snap/go/6633/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000114e40, 0xc00030c658, 0x9, 0x9, 0xc000a15d18, 0x1d07900, 0x97dceb)
	/snap/go/6633/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1e59c00, 0xc000114e40, 0xc00030c658, 0x9, 0x9, 0x9, 0xc00007e060, 0x0, 0x1e5a000)
	/snap/go/6633/src/io/io.go:314 +0x87
io.ReadFull(...)
	/snap/go/6633/src/io/io.go:333
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc00030c658, 0x9, 0x9, 0x1e59c00, 0xc000114e40, 0x0, 0x0, 0xc0009fc9f0, 0x0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00030c620, 0xc0009fc9f0, 0x0, 0x0, 0x0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000a15fa8, 0x0, 0x0)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1794 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000102c00)
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1716 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:695 +0x66e
``` 

My setup is pretty standard, with the only difference that I am behind a proxy configured in containerd-env.

``` 
root@tux0058:~# cat /var/snap/microk8s/current/args/containerd-env
# To start containerd behind a proxy you need to add an HTTPS_PROXY
# environment variable in this file. HTTPS_PROXY is of the following form:
# HTTPS_PROXY=http://username:password@proxy:port/
# where username: and password@ are optional. eg:
#
# HTTPS_PROXY=https://squid.internal:3128
#
# You may also want to set NO_PROXY to include the cluster-cidr and the services-cidr
# as specified in /var/snap/microk8s/current/args/kube-proxy and
# /var/snap/microk8s/current/args/kube-apiserver
#
# NO_PROXY=10.1.0.0/16,10.152.183.0/24
#
# Remember to restart MicroK8s after editing this file:
#
# sudo microk8s stop; sudo microk8s start
#
#

# Attempt to change the maximum number of open file descriptors
# this get inherited to the running containers
#
ulimit -n 65536 || true

# Attempt to change the maximum locked memory limit
# this get inherited to the running containers
#
ulimit -l 16384 || true

no_proxy=/var/snap/microk8s/common/run/containerd.sock,*.dol.telekom.de,dol.telekom.de,10.1.195.*,/var/run/docker.sock,vm012.bn.detemobil.de,vm012,vm013.bn.detemobil.de,vm013,127.0.0.1,lbs-nginx-tls,lbs-gmpc-tls,localhost,mz212vm112.mds.t-mobile.net,10.152.183.1,tux0058,10.1.0.0/16,10.152.183.0/24,10.1.195.58
NO_PROXY=/var/snap/microk8s/common/run/containerd.sock,*.dol.telekom.de,dol.telekom.de,10.1.195.*,/var/run/docker.sock,vm012.bn.detemobil.de,vm012,vm013.bn.detemobil.de,vm013,127.0.0.1,lbs-nginx-tls,lbs-gmpc-tls,localhost,mz212vm112.mds.t-mobile.net,10.152.183.1,tux0058,10.1.0.0/16,10.152.183.0/24,10.1.195.58
HTTP_PROXY=http://10.1.210.10:3128
HTTPS_PROXY=http://10.1.210.10:3128
http_proxy=http://10.1.210.10:3128
https_proxy=http://10.1.210.10:3128
ftp_proxy="ftp://10.1.210.10:3128/"
socks_proxy="socks://10.1.210.10:3128/"
ftp_proxy="ftp://10.1.210.10:3128/"
``` 

I have completely run out of ideas here. A similar bug report is https://github.com/ubuntu/microk8s/issues/461 , nut none of the suggestions there seem to work for me.

[
[inspection-report-20201124_113419.tar.gz](https://github.com/ubuntu/microk8s/files/5589216/inspection-report-20201124_113419.tar.gz)
](url)

**Comment by balchua** [comment]
I think that file `var/snap/microk8s/current/args/containerd-env` is only for the containerd.

According to the [docs](https://microk8s.io/docs/install-proxy)

You may want to also add `no_proxy` in `/etc/environment`

>Host configuration and clustering behind a proxy
Any nodes where MicroK8s is installed on need to be included in the `no_proxy` environment variable of the host. Usually this can be be done by editing `/etc/environment`.

**Comment by dirkm** [comment]
That was it.Thanks a lot !!

For future reference: adding the IP of my host in numerical form to no_proxy in /etc/environment fixed the issue for me.

I am not 100% certain but I think /etc/environment is deprecated (at least on Fedora/Ubuntu). Typically those variables are written in a file in the directory /etc/profile.d

**Comment by balchua** [comment]
@dirkm im closing this, now that it has resolved your problem.  Feel free to open a new one when you encounter some issue.
Thanks for using MicroK8s.
