### ISSUE TITLE
issue installing microk8s with homebrew on bigsur

### ISSUE THREAD

**Issue by degenerate999** [ubuntu/microk8s#1792]
Having the following error when trying to install microk8s. Ive removed and installed the latest pip. When I do a pip --version I get 20.3 so unsure as to why it still says 20.2.4. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 397, in run
    installed = install_given_reqs(
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/usr/local/Cellar/microk8s/2.0.1/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/Cellar/microk8s/2.0.1/libexec/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-bgwvhehe/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-bgwvhehe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-x814f4l1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/microk8s/2.0.1/libexec/include/site/python3.9/simplejson Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/Cellar/microk8s/2.0.1/libexec/bin/python -m pip install --upgrade pip' command.
Removed build tracker: '/private/tmp/pip-req-tracker-nsjya337'

**Comment by joedborg** [comment]
Hi @degenerate999 

Can you please try running 

```
brew reinstall python3
```

This will make sure your Python environment is purely python3 from brew and not mixing with MacOS's.

**Comment by degenerate999** [comment]
Wow - this worked, thanks so much. Hero.

**Comment by joedborg** [comment]
No problem, we've seen some similar, but not exactly the same, issues after the upgrade to 11.  Have fun and thanks for filing the bug.
