### ISSUE TITLE
A few times a day, communications is lots to pods, new IP address assigned to mysql

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#1813]
This mysql image is rock solid on docker-compose, staying up for months, only going down when I do so.  It looks like 
1) communication is interrupted a few times a day, 
2) when trying to get logs during the blip, microk8s reports Error from server (NotFound): the server could not find the requested resource 
3) then logs show other pods getaddrinfo ENOTFOUND mysql-service mysql-service

This problem was first discovered by running only MySQL in microk8s kubenetes deployment. Then running MySQL workbench from the desktop using address provided by microk8s kubectl get pods -o wide.  Twice a day I would loose communications and need to set a new IP address.

The host is ubuntu 18.04 will almost nothing install, my development done in docker-compose and now microk8s.
Microk8s installed directly on ubuntu, no VM. Nothing fancy.

**microk8s kubectl describe pod mysql-deployment-756f9d8cdf-8kzdw**
Notice the 11 minute age.

    Events:
      Type    Reason          Age   From     Message
      ----    ------          ----  ----     -------
      Normal  SandboxChanged  11m   kubelet  Pod sandbox changed, it will be killed and re-created.
      Normal  Pulled          11m   kubelet  Container image "mysql:5.7" already present on machine
      Normal  Created         11m   kubelet  Created container mysql-container
      Normal  Started         11m   kubelet  Started container mysql-container

**microk8s get pods -o wide**
Notice the 41h and also the IP address changed about 11 minutes ago.

    NAME                                        READY   STATUS    RESTARTS   AGE   IP             NODE                   NOMINATED NODE   READINESS GATES
    
    mysql-deployment-756f9d8cdf-8kzdw           1/1     Running   3          41h   10.1.167.149   john-trx40-designare   <none>           <none>

**microk8s kubectl logs  mysql-deployment-756f9d8cdf-8kzdw**

report a number of 

    2020-12-08T02:10:10.264100Z 32 [Note] Aborted connection 32 to db: 'jjg_script_db' user: 'root' host: '10.1.167.159' (Got an error reading communication packets)

Other pods report failing dhcp lookup, then crash and get recreated ..

It feels like IP lease is running out, but I would rather look at a log rather than speculate.
Say this because sql pod age keeps increasing.  The same exact sql image and data stay operational for months on docker-compose. Frequency is not tied to traffic.

sudo microk8s inspect produces lots of logs files, look at everyone but
may have missed the critical events because of the large number of logs and not sure where 
to look.

**Where do I look up logs for reason / trigger causing SandboxChanged?
If my guess is correct, that its an issue with IP lease, where would I find IP allocation logs for microk8s kubernetes ?**

My setup is a ubuntu 18.04 host with very little installed excepted for docker, docker-compose, git, visual studio code and microk8s kubernetes.

Everything recovers, but the interuption is anoying, and not knowing where to look is driving me nuts.

**ingress**

    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
      name: ingress-myservice-jjg
      annotations:
        # use the shared ingress-nginx
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/affinity: "cookie"
        nginx.ingress.kubernetes.io/affinity-mode: "balanced" # "persistent"
        # added next 2 lines for secured https after I got a certificate
        certmanager.k8s.io/cluster-issuer: "letsencrypt-issuer"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
    spec:
      # added tls lines for secured https after I got a certificate
      tls:
        - hosts:
            - ancient-script.org
            - www.ancient-script.org
          secretName: ancient-script-org-crt-secret
      rules:
      - host: ancient-script.org
        http:
          paths:
          - path: /
            backend:
              serviceName: express-service
              servicePort: 3000
      - host: www.ancient-script.org
        http:
          paths:
          - path: /
            backend:
              serviceName: express-service
              servicePort: 3000

**Deployment**

    apiVersion: v1
    kind: Service
    metadata:
      name: mysql-service
    spec:
      ports:
      - protocol: TCP     # default is TCP
        port: 3306        # incomming port from within kubernetes
        targetPort: 3306  # default, port on the pod
      selector:
        app: mysql-pod
      clusterIP: None
    ---
    apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
    kind: Deployment
    metadata:
      name: mysql-deployment
    spec:
      selector:
        matchLabels:
          app: mysql-pod
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: mysql-pod
        spec:
          containers:
          - image: mysql:5.7
            name: mysql-container
            args: 
            - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'todochange'
            - name: MYSQL_DATABASE
              value: ancient_script_db
            ports:
            - containerPort: 3306
              name: mysql
            volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim

**logs from MySQL about the same time the IP changed**

    2020-12-10T19:39:43.795268Z 44 [Note] Aborted connection 44 to db: 'ancient_script_db' user: 'root' host: '10.1.167.141' (Got an error reading communication packets)
    2020-12-10T19:39:43.796587Z 43 [Note] Aborted connection 43 to db: 'ancient_script_db' user: 'root' host: '10.1.167.141' (Got an error reading communication packets)
    2020-12-10T19:39:43.796761Z 41 [Note] Aborted connection 41 to db: 'ancient_script_db' user: 'root' host: '10.1.167.141' (Got an error reading communication packets)
    2020-12-10T19:39:43.796831Z 38 [Note] Aborted connection 38 to db: 'ancient_script_db' user: 'root' host: '10.1.167.141' (Got an error reading communication packets)
    2020-12-10T19:39:43.796889Z 42 [Note] Aborted connection 42 to db: 'ancient_script_db' user: 'root' host: '10.1.167.141' (Got an error reading communication packets)

**from another incident, they occur twice daily:**

Notice error message from microk8s when trying to get logs from another pods that uses MySQL, when microk9s finally allows logs, the logs show dhcp issus.

    john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe$ k describe pod express-deployment-64947b66b9-84vzc
    Name:         express-deployment-64947b66b9-84vzc
    Namespace:    default
    Priority:     0
    Node:         john-trx40-designare/99.153.71.9
    Start Time:   Fri, 11 Dec 2020 12:27:13 -0600
    Labels:       app=express-pod
                  pod-template-hash=64947b66b9
    Annotations:  cni.projectcalico.org/podIP: 10.1.167.153/32
                  cni.projectcalico.org/podIPs: 10.1.167.153/32
    Status:       Running
    IP:           10.1.167.153
    IPs:
      IP:           10.1.167.153
    Controlled By:  ReplicaSet/express-deployment-64947b66b9
    Containers:
      express:
        Container ID:   containerd://e9d178313638d3a8985caef57ae6e45f2b37b5ae08032e0eeba01c30a12676ce
        Image:          localhost:32000/express-server:20201211d
        Image ID:       localhost:32000/express-server@sha256:95fcc8679727820cff428f657ea7c32811681c2782e3692fbad0041ffcd3d935
        Port:           <none>
        Host Port:      <none>
        State:          Running
          Started:      Fri, 11 Dec 2020 12:27:15 -0600
        Ready:          True
        Restart Count:  0
        Environment:
          mySQL_connection_limit:                  200
          mySQL_host:                              mysql-service
          mySQL_port:                              3306
          mySQL_user:                              root
          mySQL_password:                          xxxxxxx
          ROOT_PATH_user_files:                    /user_files
          ROOT_PATH_crop_images:                   /crop_images
          ROOT_PATH_bulk_input_AI_transcriptions:  /temp/FEB_2020_AI_transcription.txt #is this used?
          ROOT_PATH_CURRICULUM:                    /temp/curriculum/  #is this used?
          ROOT_PATH_transcribed_words:             /transcription_db/crops_sets/transcribed_words/ #is this used?
          ROOT_PATH_train_test:                    /transcription_db/train_test #is this used?
          IMAGE_SERVICE_ADDRESS:                   image-service
          TRANSCRIBE_SERVICE_ADDRESS:              transcription-service
          LOGIN_COOKIE_NAME:                       ancient_script_signed_login_token
        Mounts:
          /crop_images from name-ci (rw)
          /user_files from name-uf (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from default-token-qnqqd (ro)
    Conditions:
      Type              Status
      Initialized       True 
      Ready             True 
      ContainersReady   True 
      PodScheduled      True 
    Volumes:
      name-uf:
        Type:          HostPath (bare host directory volume)
        Path:          /mnt/disk2/Documents/help_me_transcribe/production/pv/user_files
        HostPathType:  
      name-ci:
        Type:          HostPath (bare host directory volume)
        Path:          /mnt/disk2/Documents/help_me_transcribe/production/pv/crop_images
        HostPathType:  
      default-token-qnqqd:
        Type:        Secret (a volume populated by a Secret)
        SecretName:  default-token-qnqqd
        Optional:    false
    QoS Class:       BestEffort
    Node-Selectors:  <none>
    Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                     node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
    Events:
      Type    Reason     Age   From               Message
      ----    ------     ----  ----               -------
      Normal  Scheduled  28m   default-scheduler  Successfully assigned default/express-deployment-64947b66b9-84vzc to john-trx40-designare
      Normal  Pulling    28m   kubelet            Pulling image "localhost:32000/express-server:20201211d"
      Normal  Pulled     28m   kubelet            Successfully pulled image "localhost:32000/express-server:20201211d" in 446.977029ms
      Normal  Created    28m   kubelet            Created container express
      Normal  Started    28m   kubelet            Started container express
    john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe$ k logs express-deployment-64947b66b9-84vzc
    Error from server (NotFound): the server could not find the requested resource ( pods/log express-deployment-64947b66b9-84vzc)
    
    john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe$ k logs express-deployment-64947b66b9-84vzc
    process.env.mySQL_host = mysql-service
    process.env.mySQL_port = 3306
    process.env.mySQL_user = root
    process.env.mySQL_password = xxxxxxx
    initializing socketApi.js
    FOCUS
    TODO, need to process all user files not just john_grabner
    Scanning all files to make sure present in database ... this will take some time
    Listening on port 3000 when launched native or from docker networks, maybe remapped to host in docker-compose
    Unhandled Rejection at: Promise Promise {
      <rejected> { Error: getaddrinfo ENOTFOUND mysql-service mysql-service:3306
        at errnoException (dns.js:55:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
        --------------------
        at Protocol._enqueue (/app/src/help-me-transcribe-server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
        at Protocol.handshake (/app/src/help-me-transcribe-server/node_modules/mysql/lib/protocol/Protocol.js:52:23)
        at PoolConnection.connect (/app/src/help-me-transcribe-server/node_modules/mysql/lib/Connection.js:130:18)
        at Pool.getConnection (/app/src/help-me-transcribe-server/node_modules/mysql/lib/Pool.js:48:16)
        at Promise (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:47:22)
        at new Promise (<anonymous>)
        at getConnection (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:42:16)
        at query (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:77:12)
        at query (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:74:16)
        at Object.query_one_or_null (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:101:12)
      code: 'ENOTFOUND',
      errno: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mysql-service',
      host: 'mysql-service',
      port: 3306,
      fatal: true } } reason: { Error: getaddrinfo ENOTFOUND mysql-service mysql-service:3306
        at errnoException (dns.js:55:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
        --------------------
        at Protocol._enqueue (/app/src/help-me-transcribe-server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
        at Protocol.handshake (/app/src/help-me-transcribe-server/node_modules/mysql/lib/protocol/Protocol.js:52:23)
        at PoolConnection.connect (/app/src/help-me-transcribe-server/node_modules/mysql/lib/Connection.js:130:18)
        at Pool.getConnection (/app/src/help-me-transcribe-server/node_modules/mysql/lib/Pool.js:48:16)
        at Promise (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:47:22)
        at new Promise (<anonymous>)
        at getConnection (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:42:16)
        at query (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:77:12)
        at query (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:74:16)
        at Object.query_one_or_null (/app/src/help-me-transcribe-server/help-me-data-access/sql.js:101:12)
      code: 'ENOTFOUND',
      errno: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'mysql-service',
      host: 'mysql-service',
      port: 3306,
      fatal: true }

[inspection-report-20201211_130910.tar.gz](https://github.com/ubuntu/microk8s/files/5681136/inspection-report-20201211_130910.tar.gz)
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by johngrabner** [comment]
same issue as https://github.com/ubuntu/microk8s/issues/1866
