### ISSUE TITLE
Problems installing on MacOS

### ISSUE THREAD

**Issue by ct27stf** [ubuntu/microk8s#1882]
MacOs Catalina 10.15.7

did brew reinstall python
and brew reinstall python3

still getting this error

```==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1
Using pip 20.3.3 from /usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
Non-user install by explicit request
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-v_mnupxi
Created temporary directory: /private/tmp/pip-req-tracker-augdqln7
Initialized build tracking at /private/tmp/pip-req-tracker-augdqln7
Created build tracker: /private/tmp/pip-req-tracker-augdqln7
Entered build tracker: /private/tmp/pip-req-tracker-augdqln7
Created temporary directory: /private/tmp/pip-install-c_8x33jz
Processing /private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1
  Created temporary directory: /private/tmp/pip-req-build-5ps_lo78
  Added file:///private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1 to build tracker '/private/tmp/pip-req-tracker-augdqln7'
    Running setup.py (path:/private/tmp/pip-req-build-5ps_lo78/setup.py) egg_info for package from file:///private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1
    Created temporary directory: /private/tmp/pip-pip-egg-info-za8r8riq
    Running command python setup.py egg_info
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-wheel-463_w4wq/vcversioner_4bd4f10783974c4bac03c9551bec888f/setup.py'"'"'; __file__='"'"'/private/tmp/pip-wheel-463_w4wq/vcversioner_4bd4f10783974c4bac03c9551bec888f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-mtknp73x
           cwd: /private/tmp/pip-wheel-463_w4wq/vcversioner_4bd4f10783974c4bac03c9551bec888f/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for vcversioner
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpgeqbrfdi', '--quiet', 'vcversioner']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-5ps_lo78/setup.py", line 30, in <module>
        setup(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpgeqbrfdi', '--quiet', 'vcversioner']' returned non-zero exit status 1.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1 from build tracker '/private/tmp/pip-req-tracker-augdqln7'
Removed build tracker: '/private/tmp/pip-req-tracker-augdqln7'
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/local/Homebrew/Library/Homebrew/debrew.rb:18:in `raise'
BuildError: Failed executing: /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--jsonschema-20210111-38670-1mbhj17/jsonschema-2.5.1```

```
==> Formula
Tap: ubuntu/microk8s
Path: /usr/local/Homebrew/Library/Taps/ubuntu/homebrew-microk8s/Formula/microk8s.rb
==> Configuration
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4465bb1720ee1c1dfe7c7585fc8d32b9f045d822
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.BC54rFT17s/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
/usr/bin/curl --version
Curl: 7.64.1 => /usr/bin/curl
/usr/libexec/java_home --xml --failfast
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/tcl-tk:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/tcl-tk/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/tcl-tk/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.9/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: ubuntu/microk8s/microk8s 2.0.2 did not build
```

**Comment by joedborg** [comment]
Hi @ct27stf can you please try running `brew reinstall python` and then re-trying microk8s?

Thanks,
Joe

**Comment by ct27stf** [comment]
hi @joedborg like I said, I did 
```
brew reinstall python
and brew reinstall python3
```
with no success

**Comment by joedborg** [comment]
Apologies @ct27stf, I missed that.  Seems to effect others too https://github.com/ubuntu/microk8s/issues/1883

I need to try and source a non Big Sur machine to test on as that's likely the issue here.

**Comment by joedborg** [comment]
Hi @ct27stf and @sgerov,

If either of you have time, could you please try to clone the MicroK8s repo, `cd` into installer and try to run 

```
python ./setup.py bdist_wheel
```

to see if it creates a `.whl` in `./dist`.

Many thanks,
Joe

**Comment by joedborg** [comment]
Seems to be the update from Python 3.8 to 3.9.  Now working on a fix.

**Comment by joedborg** [comment]
Hi all, this should now be fixed.  Thank you for you patience.

This was due to a, luckily a no longer used, dependency not building on the recently released, to homebrew, Python 3.9.1 (https://github.com/Homebrew/homebrew-core/commits/b795663611e927121b042600f9e15e63b6e992b0/Formula/python%403.9.rb). 

You should now be able to run `brew install ubuntu/microk8s/microk8s`.  It's probably worth running a `brew cleanup -s` before hand to make sure all the cache is invalidated.

Please let me know if there are any further issues revolving around this. 

Many thanks,
Joe

**Comment by oluies** [comment]
Works for me

**Comment by ct27stf** [comment]
yes! v2.0.3 did it. Thanks!

**Comment by sgerov** [comment]
Worked for me as well, thanks for the quick fix

**Comment by joedborg** [comment]
Thanks all!
