### ISSUE TITLE
Error on brew install ubuntu/microk8s/microk8s 

### ISSUE THREAD

**Issue by sgerov** [ubuntu/microk8s#1883]
When running `brew install ubuntu/microk8s/microk8s` I get the following error:

```
brew install ubuntu/microk8s/microk8s


Updating Homebrew...
==> Installing microk8s from ubuntu/microk8s
==> Downloading https://files.pythonhosted.org/packages/b8/e2/a3a86a67c3fc8249ed305fc7b7d290ebe5e4d46ad45573884761ef4dea7b/certifi-2020.4.5.1.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/bffbbd7ee41c28944ae86910ee924f450d919d2915c7825db25095d2381ed7a8--certifi-2020.4.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/729f15182b3d73a61df6c5b70fb07736c3a57abd09b7fde46af074f5787e42dd--click-7.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/aba6aff23ff0ee31279add4664bd5f407a590ad2a0ac29747f5e569a51e8cedf--idna-2.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/58/0d/c816f5ea5adaf1293a1d81d32e4cdfdaf8496973aa5049786d7fdb14e7e7/jsonschema-2.5.1.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/968a9462d392b9f0f5fbeaf0bd717c942279f76e63daf6f0fa733a7a78ced88a--jsonschema-2.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/71/fc/7c8e01f41a6e671d7b11be470eeb3d15339c75ce5559935f3f55890eec6b/progressbar33-2.4.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/4f671409b54c153caf3929a5a9210e036096c54fdbd567619affcd6156fbc00d--progressbar33-2.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/97/10/92d25b93e9c266c94b76a5548f020f3f1dd0eb40649cb1993532c0af8f4c/requests-2.20.0.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/b41510c418b03cfb53cff6ccb749c551377cb242100e0f7a6ed9a1419e5605c5--requests-2.20.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f3/94/67d781fb32afbee0fffa0ad9e16ad0491f1a9c303e14790ae4e18f11be19/requests-unixsocket-0.1.5.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/079163d4a38fd48851f914d3018dc464b95e7ef341f9cc40998303f4bf7f0bfa--requests-unixsocket-0.1.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/c394b64dcdc4fbf8ad5b5bd86402b48123ae4275fdc917d0b0c3a2934bc0cc7f--simplejson-3.8.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/8dd2734c2fe98588801dd538809a3da7987291bd858dfbad935cfabd46090cbb--toml-0.10.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fd/fa/b21f4f03176463a6cccdb612a5ff71b927e5224e83483012747c12fc5d62/urllib3-1.24.2.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/17afd9f91be6a5b62202c12b7e2fdba3860182bd630f4912fd306850ff49619c--urllib3-1.24.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/553d732b4cf117039b60aab1f75ac3e6f6869a9fa3127b4107984fa5b084a00b--wheel-0.34.2.tar.gz
==> Downloading https://github.com/ubuntu/microk8s/archive/installer-v2.0.2.tar.gz
Already downloaded: /Users/sava.gerov/Library/Caches/Homebrew/downloads/bff38bd672dde8a335e07043c2ffd56bdb0d93431d70e98e1efe514ce14cf7fc--microk8s-installer-v2.0.2.tar.gz
==> python3 -m venv /usr/local/Cellar/microk8s/2.0.2/libexec
==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--certifi-20210111-70030-kahe4b/certifi-2020.4.5.1
==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--chardet-20210111-70030-y30e4n/chardet-3.0.4
==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--click-20210111-70030-1kbhnm3/click-7.1.2
==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--idna-20210111-70030-1e1mk0e/idna-2.7
==> /usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip install -v --no-deps --no-binary :all: --no-user --ignore-installed /private/tmp/microk8s--jsonschema-20210111-70030-16mm6ow/jsonschema-2.5.1
Last 15 lines from /Users/sava.gerov/Library/Logs/Homebrew/microk8s/06.pip:
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///private/tmp/microk8s--jsonschema-20210111-70030-16mm6ow/jsonschema-2.5.1 from build tracker '/private/tmp/pip-req-tracker-u146vztj'
Removed build tracker: '/private/tmp/pip-req-tracker-u146vztj'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ubuntu/homebrew-microk8s/issues
```

I tried `brew reinstall python`, `brew postinstall python3` and `pip3 install setuptools` with no luck.

My machine: Mac OS Catalina 10.15.7, 2020 Macbook pro

Any idea what might be wrong? Thanks!

**Comment by sgerov** [comment]
Full log:

```
2021-01-11 17:44:29 +0000

/usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip
install
-v
--no-deps
--no-binary
:all:
--no-user
--ignore-installed
/private/tmp/microk8s--jsonschema-20210111-79110-1as4mbj/jsonschema-2.5.1

Using pip 20.3.3 from /usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
Non-user install by explicit request
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-4_0w2mye
Created temporary directory: /private/tmp/pip-req-tracker-wxvlkwqk
Initialized build tracking at /private/tmp/pip-req-tracker-wxvlkwqk
Created build tracker: /private/tmp/pip-req-tracker-wxvlkwqk
Entered build tracker: /private/tmp/pip-req-tracker-wxvlkwqk
Created temporary directory: /private/tmp/pip-install-3mzwqt4h
Processing /private/tmp/microk8s--jsonschema-20210111-79110-1as4mbj/jsonschema-2.5.1
  Created temporary directory: /private/tmp/pip-req-build-krsot53_
  Added file:///private/tmp/microk8s--jsonschema-20210111-79110-1as4mbj/jsonschema-2.5.1 to build tracker '/private/tmp/pip-req-tracker-wxvlkwqk'
    Running setup.py (path:/private/tmp/pip-req-build-krsot53_/setup.py) egg_info for package from file:///private/tmp/microk8s--jsonschema-20210111-79110-1as4mbj/jsonschema-2.5.1
    Created temporary directory: /private/tmp/pip-pip-egg-info-g1nnsmb9
    Running command python setup.py egg_info
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-wheel-xrckkqdu/vcversioner_493f8aa7bbf94d59ad96fb97bfd31640/setup.py'"'"'; __file__='"'"'/private/tmp/pip-wheel-xrckkqdu/vcversioner_493f8aa7bbf94d59ad96fb97bfd31640/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-m6h60c3e
           cwd: /private/tmp/pip-wheel-xrckkqdu/vcversioner_493f8aa7bbf94d59ad96fb97bfd31640/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for vcversioner
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpnbjzity4', '--quiet', 'vcversioner']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-krsot53_/setup.py", line 30, in <module>
        setup(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpnbjzity4', '--quiet', 'vcversioner']' returned non-zero exit status 1.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///private/tmp/microk8s--jsonschema-20210111-79110-1as4mbj/jsonschema-2.5.1 from build tracker '/private/tmp/pip-req-tracker-wxvlkwqk'
Removed build tracker: '/private/tmp/pip-req-tracker-wxvlkwqk'

HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20b2aa89d1b03d7c2083cfd515d39d11af334aee
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/tcl-tk:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/tcl-tk/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/tcl-tk/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.9/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

I tried to reinstall `wheel` with `pip` and `pip3` with no luck either.

**Comment by joedborg** [comment]
Hi @sgerov can you please try running brew reinstall python and then re-trying microk8s?

Thanks,
Joe

**Comment by sgerov** [comment]
hey @joedborg as mentioned in my first comment that's the first thing I tried with no luck :( also tried `brew link --overwrite python@3.9` now but didn't help

**Comment by joedborg** [comment]
Apologies @sgerov, in that case it seems to be the same as https://github.com/ubuntu/microk8s/issues/1882, so I'm going to move the thread to there :)
