### ISSUE TITLE
A node in my cluster hit very high memory pressure, wedged, and apparently took the `snap` system  down wiith it?!

### ISSUE THREAD

**Issue by kquinsland** [ubuntu/microk8s#1884]
### Background:

I have a 6 node cluster, all using the 'built in' HA system. Back when the auto-clustering was introduced, i, like many, had some stability issues. Subsequent release have more or less made those stability issue a thing of the past. (see: https://github.com/ubuntu/microk8s/issues/1598)

I had several weeks of cluster up time until just the other day when the web interface I was using indicated that it lost its connection to the back end. The back end just so happened to be hosted on the node that crashed.

I opened the 'pre-built' dashboards in Grafana for keeping an eye on the Prometheus metrics for the cluster and i saw *very high* memory pressure on the node in question. I could not SSH into the node and a physical inspection showed the HDD activity LED *on* - not flashing.

![node02](https://user-images.githubusercontent.com/1808375/104222742-92cf0380-53f7-11eb-8528-85afc628cc6c.png)

![USE_Method_node02](https://user-images.githubusercontent.com/1808375/104222873-c27e0b80-53f7-11eb-9596-db91c6ab752e.png)

![USE_Method_Cluster](https://user-images.githubusercontent.com/1808375/104222896-ca3db000-53f7-11eb-9d8a-94f3b08d4269.png)

I was not able to open a SSH connection; was able to force the box to power down. After it came back up, was able to SSH in and the `microk8s` snap is _FUBAR_:

After the hard reboot, got in and tried to figure out what went wrong:

```shell
karl@node02:~$ sudo su
[sudo] password for karl:

root@node02:/home/karl# kubectl get no
The connection to the server node02-IPv4-Here:16443 was refused - did you specify the right host or port?

root@node02:/home/karl# microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
root@node02:/home/karl# microk8s inspect
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
Inspecting Certificates
Inspecting services
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-cluster-agent/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-cluster-agent/systemctl.log: No such file or directory
 FAIL:  Service snap.microk8s.daemon-cluster-agent is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-cluster-agent
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-containerd/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-containerd/systemctl.log: No such file or directory
 FAIL:  Service snap.microk8s.daemon-containerd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-containerd
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-apiserver/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-apiserver/systemctl.log: No such file or directory
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-apiserver-kicker/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-apiserver-kicker/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-apiserver-kicker is running
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-control-plane-kicker/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-control-plane-kicker/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-control-plane-kicker is running
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-proxy/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-proxy/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-proxy is running
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-kubelet/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-kubelet/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-kubelet is running
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-scheduler/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-scheduler/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-scheduler is running
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 19: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-controller-manager/journal.log: No such file or directory
/snap/microk8s/1856/inspect.sh: line 20: /var/snap/microk8s/1856/inspection-report/snap.microk8s.daemon-controller-manager/systemctl.log: No such file or directory
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
cp: cannot create directory '/var/snap/microk8s/1856/inspection-report': Read-only file system
Inspecting AppArmor configuration
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 39: /var/snap/microk8s/1856/inspection-report/apparmor/dmesg: No such file or directory
/snap/microk8s/1856/inspect.sh: line 40: /var/snap/microk8s/1856/inspection-report/apparmor/aa-status: No such file or directory
Gathering system information
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
  Copy processes list to the final report tarball
/snap/microk8s/1856/inspect.sh: line 68: /var/snap/microk8s/1856/inspection-report/sys/ps: No such file or directory
  Copy snap list to the final report tarball
/snap/microk8s/1856/inspect.sh: line 70: /var/snap/microk8s/1856/inspection-report/sys/snap-version: No such file or directory
/snap/microk8s/1856/inspect.sh: line 71: /var/snap/microk8s/1856/inspection-report/sys/snap-list: No such file or directory
  Copy VM name (or none) to the final report tarball
/snap/microk8s/1856/inspect.sh: line 74: /var/snap/microk8s/1856/inspection-report/sys/vm_name: No such file or directory
  Copy disk usage information to the final report tarball
/snap/microk8s/1856/inspect.sh: line 77: /var/snap/microk8s/1856/inspection-report/sys/disk_usage: No such file or directory
  Copy memory usage information to the final report tarball
/snap/microk8s/1856/inspect.sh: line 80: /var/snap/microk8s/1856/inspection-report/sys/memory_usage: No such file or directory
  Copy server uptime to the final report tarball
/snap/microk8s/1856/inspect.sh: line 83: /var/snap/microk8s/1856/inspection-report/sys/uptime: No such file or directory
  Copy current linux distribution to the final report tarball
/snap/microk8s/1856/inspect.sh: line 86: /var/snap/microk8s/1856/inspection-report/sys/lsb_release: No such file or directory
  Copy openSSL information to the final report tarball
/snap/microk8s/1856/inspect.sh: line 89: /var/snap/microk8s/1856/inspection-report/sys/openssl: No such file or directory
  Copy network configuration to the final report tarball
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
/snap/microk8s/1856/inspect.sh: line 55: /var/snap/microk8s/1856/inspection-report/network/netstat: No such file or directory
/snap/microk8s/1856/inspect.sh: line 56: /var/snap/microk8s/1856/inspection-report/network/ifconfig: No such file or directory
/snap/microk8s/1856/inspect.sh: line 57: /var/snap/microk8s/1856/inspection-report/network/iptables: No such file or directory
/snap/microk8s/1856/inspect.sh: line 58: /var/snap/microk8s/1856/inspection-report/network/iptables-S: No such file or directory
/snap/microk8s/1856/inspect.sh: line 59: /var/snap/microk8s/1856/inspection-report/network/iptables-L: No such file or directory
Inspecting kubernetes cluster
  Inspect kubernetes cluster
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
tee: /var/snap/microk8s/1856/inspection-report/k8s/version: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/k8s/cluster-info: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/k8s/cluster-info-dump: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/k8s/get-all: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/k8s/get-pv: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/k8s/get-pvc: No such file or directory
Inspecting juju
  Inspect Juju
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
tee: /var/snap/microk8s/1856/inspection-report/juju/status: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/juju/debug.log: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/juju/controller.log: No such file or directory
Inspecting kubeflow
  Inspect Kubeflow
mkdir: cannot create directory ‘/var/snap/microk8s/1856/inspection-report’: Read-only file system
tee: /var/snap/microk8s/1856/inspection-report/kubeflow/pods.yaml: No such file or directory
tee: /var/snap/microk8s/1856/inspection-report/kubeflow/pods.describe: No such file or directory

Building the report tarball
gzip: /var/snap/microk8s/1856/inspection-report-20210108_201711.tar: No such file or directory
  Report tarball is at /var/snap/microk8s/1856/inspection-report-20210108_201711.tar.gz
```

It looks like the inspection report was not created:

```shell
root@node02:/home/karl# cp  /var/snap/microk8s/1856/inspection-report-20210108_201711.tar.gz .
cp: cannot stat '/var/snap/microk8s/1856/inspection-report-20210108_201711.tar.gz': No such file or directory
root@node02:/home/karl# ls /var/snap/microk8s/1856/
args  certs  credentials  juju  juju-home  opt  var
```

The disk is _plenty_ empty so the read-only file system errors are caused by something else:

```shell
root@node02:/home/karl# df
Filesystem                        1K-blocks     Used Available Use% Mounted on
udev                                3988136        0   3988136   0% /dev
tmpfs                                806412    19436    786976   3% /run
/dev/mapper/ubuntu--vg-ubuntu--lv 121765536 29184528  86352632  26% /
tmpfs                               4032052        0   4032052   0% /dev/shm
tmpfs                                  5120        0      5120   0% /run/lock
tmpfs                               4032052        0   4032052   0% /sys/fs/cgroup
/dev/sda2                            999320   203008    727500  22% /boot
/dev/loop0                           100224   100224         0 100% /snap/core/10577
/dev/sda1                            523248     7984    515264   2% /boot/efi
/dev/loop2                            56832    56832         0 100% /snap/core18/1944
/dev/loop1                            56704    56704         0 100% /snap/core18/1932
/dev/loop3                            73088    73088         0 100% /snap/lxd/16099
/dev/loop4                           100352   100352         0 100% /snap/core/10583
/dev/loop5                            31872    31872         0 100% /snap/snapd/10492
/dev/loop7                           209408   209408         0 100% /snap/microk8s/1791
/dev/loop6                            69376    69376         0 100% /snap/lxd/18150
/dev/loop8                           211840   211840         0 100% /snap/microk8s/1856
/dev/loop9                            31872    31872         0 100% /snap/snapd/10707
```

And after a `microk8s reset` then a `microk8s join`:

```shell
root@node02:/#  microk8s join node01-IPv4-here:25000/f77cfa1d99a33b20ed3d2f9a73c4882a
Contacting cluster at node01-IPv4-here
Traceback (most recent call last):
  File "/snap/microk8s/1856/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/1856/scripts/cluster/join.py", line 875, in join_dqlite
    store_cert("ca.crt", info["ca"])
  File "/snap/microk8s/1856/scripts/cluster/join.py", line 709, in store_cert
    shutil.copyfile(file_with_path, backup_file_with_path)
  File "/snap/microk8s/1856/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/var/snap/microk8s/1856/certs/ca.crt.backup'
```

As there are 5 other healthy nodes in the cluster, I'm not going to bother w/ a manual recovery; i'll just `microk8s reset` and then `add-node`... Except is seems that the snap runtime is also hosed:

```shell
root@node02:/# snap remove microk8s
error: cannot communicate with server: timeout exceeded while waiting for response
```

It looks like there are a few other people out there that have run into this specific error,  but it looks like the fastest path forward for this node is just a complete reformat/install of the OS.

I'm already considering the node a 'loss' so i'm not expecting support so much as asking if there's anything I can provide forensically. What - if anything - can I provide to help diagnose this issue? It does seem related to some of the crash/instability discussed in #1598; see: https://github.com/ubuntu/microk8s/issues/1598#issuecomment-723519500 

I'm not sure what files / data is still around and on-disk, but all the errors about read-only file system make me hopeful that there's still some useful or otherwise helpful data out there that can be salvaged and posted here for the benefit of developers.

Let me know if there's anything I should look for.

**Comment by Jayfrown** [comment]
@kquinsland the errors suggest your root filesystem is in fact mounted read-only, which can happen if it encounters any errors. You can verify if this is the case:

```
$ mount | grep /dev/mapper/ubuntu--vg-ubuntu--lv
```

it should give you some output that looks a bit like this

```
/dev/mapper/ubuntu--vg-ubuntu--lv on / type ext4 (rw,relatime,errors=remount-ro)
```

however if it reads `(ro,` instead of `(rw,` it means the filesystem has been mounted read-only, making it impossible to write to it, which leads to these errors. The question then becomes why is your rootfs mounted read-only. As I wrote before this can happen if there are errors while writing to the disk.

Check the output of `dmesg` if it indicates errors writing to the physical disk, it should tell you when and why it remounts the filesystem to read-only. Last time I encountered such an error it was fixed rather easily by running a filesystem check and letting it fix whatever it finds (`e2fsck -y`) and rebooting. If the errors persist, however, you might be dealing with hardware failure.

**Comment by kquinsland** [comment]
Hah! This one is on me... I did a ` dmesg | grep -C3 'mounted'` and saw

```shell
[    3.956060] EXT4-fs warning (device dm-0): ext4_clear_journal_err:5187: Filesystem error recorded from previous mount: IO failure
[    3.956068] EXT4-fs warning (device dm-0): ext4_clear_journal_err:5189: Marking fs in need of filesystem check.
[    3.958830] EXT4-fs (dm-0): recovery complete
[    3.960842] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
<...>
```

I figured that `recovery complete` meant we're good to go, but a full viewing of `dmesg` indicates that this is _not_ the case. Left for the weekend and came back to post this ticket. Just jumped back into the box and the FS is in need of a scrub:


```shell
root@node02:/# touch /forcefsck
touch: cannot touch '/forcefsck': Read-only file system
```

There's nothing of value on this node / it's trivial for me to re-install the OS so data recovery is not super important... The reason I opened this ticket is because the crash behavior was _very_ similar to behavior that was thought to be 'fixed';  api-server can't start:

```
root@node02:/# systemctl list-units | grep microk8s
  snap-microk8s-1791.mount                                                                 loaded active     mounted         Mount unit for microk8s, revision 1791
  snap-microk8s-1856.mount                                                                 loaded active     mounted         Mount unit for microk8s, revision 1856
  snap.microk8s.daemon-apiserver-kicker.service                                            loaded active     running         Service for snap application microk8s.daemon-apiserver-kicker
● snap.microk8s.daemon-apiserver.service                                                   loaded failed     failed          Service for snap application microk8s.daemon-apiserver
● snap.microk8s.daemon-cluster-agent.service                                               loaded failed     failed          Service for snap application microk8s.daemon-cluster-agent
● snap.microk8s.daemon-containerd.service                                                  loaded failed     failed          Service for snap application microk8s.daemon-containerd
  snap.microk8s.daemon-control-plane-kicker.service                                        loaded active     running         Service for snap application microk8s.daemon-control-plane-kicker
  snap.microk8s.daemon-controller-manager.service                                          loaded active     running         Service for snap application microk8s.daemon-controller-manager
  snap.microk8s.daemon-kubelet.service                                                     loaded active     running         Service for snap application microk8s.daemon-kubelet
  snap.microk8s.daemon-proxy.service                                                       loaded active     running         Service for snap application microk8s.daemon-proxy
  snap.microk8s.daemon-scheduler.service                                                   loaded active     running         Service for snap application microk8s.daemon-scheduler
```

I've repaired the SSD:

```
root@node02:/# lvscan
  ACTIVE            '/dev/ubuntu-vg/ubuntu-lv' [118.48 GiB] inherit
root@node02:/# fsck /dev/ubuntu-vg/ubuntu-lv
fsck from util-linux 2.34
e2fsck 1.45.5 (07-Jan-2020)
/dev/mapper/ubuntu--vg-ubuntu--lv contains a file system with errors, check forced.
Pass 1: Checking inodes, blocks, and sizes
Inodes that were part of a corrupted orphan linked list found.  Fix<y>? yes
Inode 263579 was part of the orphaned inode list.  FIXED.
Inode 264641 was part of the orphaned inode list.  FIXED.
Inode 268343 was part of the orphaned inode list.  FIXED.
Inode 6294369 was part of the orphaned inode list.  FIXED.
Deleted inode 6559345 has zero dtime.  Fix<y>? yes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Block bitmap differences:  -(1139942--1140250) -(1733312--1733344) -(3114880--3114967) -25198608
Fix<y>? yes
Free blocks count wrong for group #34 (13799, counted=14108).
Fix<y>? yes
Free blocks count wrong for group #52 (10131, counted=10164).
Fix<y>? yes
Free blocks count wrong for group #95 (31676, counted=31764).
Fix<y>? yes
Free blocks count wrong for group #769 (23084, counted=23085).
Fix<y>? yes
Free blocks count wrong (23145252, counted=23145683).
Fix<y>? yes
Inode bitmap differences:  -263579 -264641 -268343 -6294369 -6559345
Fix<y>? yes
Free inodes count wrong for group #32 (1331, counted=1334).
Fix ('a' enables 'yes' to all) <y>? yes
Free inodes count wrong for group #768 (4518, counted=4519).
Fix<y>? yes
Free inodes count wrong for group #800 (1546, counted=1547).
Fix<y>? yes
Free inodes count wrong (7082133, counted=7082138).
Fix<y>? yes

/dev/mapper/ubuntu--vg-ubuntu--lv: ***** FILE SYSTEM WAS MODIFIED *****
/dev/mapper/ubuntu--vg-ubuntu--lv: ***** REBOOT SYSTEM *****
/dev/mapper/ubuntu--vg-ubuntu--lv: 683878/7766016 files (0.1% non-contiguous), 7914285/31059968 blocks
```

I already removed the node from the cluster and wanted to take advantage of the "i havent tinkered with it since it fell over" state to see if there was anything that'd be of use before i started to repair / reformat the node. Assuming any repair works, the node will try to join a cluster that has already forgotten about it and i'm not sure what that'd do to any logs of value.

Post `fsck`, the node is up, but won't be able to join the cluster:


```shell
karl@node02:~$ sudo microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1856/inspection-report-20210111_230352.tar.gz
```


[inspection-report-20210111_230352.tar.gz](https://github.com/ubuntu/microk8s/files/5799222/inspection-report-20210111_230352.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @kquinsland 

> Post `fsck`, the node is up, but won't be able to join the cluster:

What do you mean by that? I can see the following pods running on node02:
```
ingress          pod/nginx-ingress-microk8s-controller-pglz2                1/1     Running   1          3m11s   10.13.88.52    node02   <none>           <none>
monitoring       pod/node-exporter-r87b6                                    2/2     Running   2          3m21s   10.13.88.52    node02   <none>           <none>
metallb-system   pod/speaker-qr6pq                                          1/1     Running   1          3m11s   10.13.88.52    node02   <none>           <none>
democratic-csi   pod/zfs-nfs-democratic-csi-node-vddbf                      3/3     Running   3          3m11s   10.13.88.52    node02   <none>           <none>
democratic-csi   pod/zfs-iscsi-democratic-csi-node-lmjtx                    3/3     Running   3          3m11s   10.13.88.52    node02   <none>           <none>
kube-system      pod/calico-node-nzzxx                                      1/1     Running   1          3m21s   10.13.88.52    node02   <none>           <none>
```

**Comment by kquinsland** [comment]
@ktsakalozos

> What do you mean by that? I can see the following pods running on node02:

After manually shutting down node02, i ran `microk8s remove --force` on a node in the healthy cluster.... which i _thought_ would have removed the node and prevented it from re-joining the cluster. The pods you listed are daemon sets that are deployed to all nodes in the cluster... but apparently the `microk8s remove node02 --force` didn't stick?

```
root@node01:/home/karl# kubectl get no
NAME     STATUS     ROLES    AGE   VERSION
node03   NotReady   <none>   60d   v1.19.5-34+8af48932a5ef06
node02   Ready      <none>   21h   v1.19.5-34+8af48932a5ef06
node06   Ready      <none>   23d   v1.19.5-34+8af48932a5ef06
node04   Ready      <none>   60d   v1.19.5-34+8af48932a5ef06
node05   Ready      <none>   60d   v1.19.5-34+8af48932a5ef06
node01   Ready      <none>   60d   v1.19.5-34+8af48932a5ef06
```

node02 auto re-joined somehow?
