### ISSUE TITLE
[Lite] Enabling dns and rbac shows error when restarting nodes

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#1930]
Using channel `latest/edge/lite`.

When doing `microk8s enable dns`,  it shows the following:

```shell
 microk8s enable dns
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
Adding argument --cluster-domain to nodes.
Configuring node 10.132.0.2
Configuring node 10.132.0.3
Adding argument --cluster-dns to nodes.
Configuring node 10.132.0.2
Configuring node 10.132.0.3
Restarting nodes.
Configuring node 10.132.0.2
Failed to perform a restart kubelet on node 10.132.0.2:25000 500
Configuring node 10.132.0.3
Failed to perform a restart kubelet on node 10.132.0.3:25000 500
DNS is enabled
```

The cluster agent logs shows this:

```shell
[2021-01-23 00:43:13,255] ERROR in app: Exception on /cluster/api/v1.0/configure [POST]
nt[21130]: Traceback (most recent call last):
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
nt[21130]:     response = self.full_dispatch_request()
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
nt[21130]:     rv = self.handle_user_exception(e)
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
nt[21130]:     reraise(exc_type, exc_value, tb)
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
nt[21130]:     raise value
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
nt[21130]:     rv = self.dispatch_request()
nt[21130]:   File "/snap/microk8s/1979/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
nt[21130]:     return self.view_functions[rule.endpoint](**req.view_args)
nt[21130]:   File "/snap/microk8s/1979/scripts/cluster/agent.py", line 432, in configure
nt[21130]:     subprocess.check_call(service('restart', service_name))
nt[21130]:   File "/snap/microk8s/1979/usr/lib/python3.5/subprocess.py", line 576, in check_call
nt[21130]:     retcode = call(*popenargs, **kwargs)
nt[21130]:   File "/snap/microk8s/1979/usr/lib/python3.5/subprocess.py", line 557, in call
nt[21130]:     with Popen(*popenargs, **kwargs) as p:
nt[21130]:   File "/snap/microk8s/1979/usr/lib/python3.5/subprocess.py", line 947, in __init__
nt[21130]:     restore_signals, start_new_session)
nt[21130]:   File "/snap/microk8s/1979/usr/lib/python3.5/subprocess.py", line 1440, in _execute_child
nt[21130]:     args = list(args)
nt[21130]: TypeError: 'NoneType' object is not iterable
```
But it seems to have restarted kubelite.

```
snap.microk8s.daemon-kubelite.service - Service for snap application microk8s.daemon-kubelite
     Loaded: loaded (/etc/systemd/system/snap.microk8s.daemon-kubelite.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-01-23 03:00:06 UTC; 58s ago
   Main PID: 193054 (kubelite)
      Tasks: 0 (limit: 19175)
     Memory: 724.4M
     CGroup: /system.slice/snap.microk8s.daemon-kubelite.service
             └─193054 /snap/microk8s/1979/kubelite --scheduler-args-file=/var/snap/microk8s/1979/args/kube-scheduler --controller-manager-a>
```

**Comment by balchua** [comment]
Closing the issue fixed by the pull request.
