### ISSUE TITLE
Failing to build ARM64 snap

### ISSUE THREAD

**Issue by tbertenshaw** [ubuntu/microk8s#2049]
Trying to build an arm64 snap, from master.

I've tried building locally on a pi4 (with 8Gb running on Ubuntu 20.10) using the same command from [the github action](https://github.com/tbertenshaw/microk8s/blob/697d2f721bef8ad215ba7f992024e8213339f49c/.github/workflows/build-snap.yml#L28)

 `sg lxd -c 'snapcraft --use-lxd'`

but it errors out after some time with.

```
Building cluster-agent
+ snapcraftctl build
Looking in links: /root/parts/cluster-agent/python-packages
Processing /root/parts/cluster-agent/python-packages/Flask-1.1.2-py2.py3-none-any.whl
Processing /root/parts/cluster-agent/python-packages/PyYAML-5.4.1.tar.gz
  Installing build dependencies ... error

  ERROR: Command errored out with exit status 1:

   command: /root/parts/cluster-agent/install/usr/bin/python3 /root/parts/cluster-agent/install/lib/python3.6/site-packa

ges/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-r9wqoe58/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /root/parts/cluster-agent/python-packages -- setuptools wheel Cython
       cwd: None
  Complete output (3 lines):
  Looking in links: /root/parts/cluster-agent/python-packages
  ERROR: Could not find a version that satisfies the requirement setuptools
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
WARNING: Discarding file:///root/parts/cluster-agent/python-packages/PyYAML-5.4.1.tar.gz. Command errored out with exit status 1: /root/parts/cluster-agent/install/usr/bin/python3 /root/parts/cluster-agent/install/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-r9wqoe58/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links /root/parts/cluster-agent/python-packages -- setuptools wheel Cython Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyYAML
ERROR: No matching distribution found for PyYAML
Failed to run '/root/parts/cluster-agent/install/usr/bin/python3 -m pip wheel --no-index --find-links /root/parts/cluster-agent/python-packages --wheel-dir /tmp/tmpufn7n4lf flask PyYAML netifaces': Exited with code 1.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

I've also tried [remote build](https://snapcraft.io/docs/remote-build).

and that errors out with.

```
Building containerd
+ set -eux
+ . /build/snapcraft-microk8s-f74d44/parts/containerd/src/set-env-variables.sh
+ set -eu
/bin/sh: 2: set: Illegal option -
Downloading 'libmnl-1.0.4.tar.bz2'   0%
Downloading 'libmnl-1.0.4.tar.bz2' 100%
Downloading 'libnftnl-1.1.8.tar.bz2'   0%
Downloading 'libnftnl-1.1.8.tar.bz2' 100%
Downloading 'iptables-1.8.6.tar.bz2'   0%
Downloading 'iptables-1.8.6.tar.bz2' 100%
Downloading 'juju-2.8.6-k8s.tar.xz'   0%
Downloading 'juju-2.8.6-k8s.tar.xz' 100%
Failed to run 'override-build': Exit code was 2.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 257, in run
    self.pull()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 223, in pull
    env=env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 100, in run_build_command
    return self.backend.run(args, env=full_env, **kwargs)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 537, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-bionic-amd64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_LOCAL_SOURCES=1', '--env', 'SNAPCRAFT_SETUP_CORE=1', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build-request-id": "lp-62642718", "build-request-timestamp": "2021-02-24T15:29:29Z", "build_url": "https://launchpad.net/~tbertenshaw/+snap/snapcraft-microk8s-f74d44/+build/1309800"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/snapcraft-microk8s-f74d44 && linux64 snapcraft pull']' returned non-zero exit status 2.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=amd64 SNAPBUILD-1309800
Scanning for processes to kill in build SNAPBUILD-1309800
```

I can supply more logs if needed.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @tbertenshaw . We should have this fixed soon.
