### ISSUE TITLE
Cluster join no longer works after enabling Cilium

### ISSUE THREAD

**Issue by ressu** [ubuntu/microk8s#2164]
During the setup process, Cilium addon disables the cni.yaml file for microk8s. This causes cluster join to fail due to CNI autodetection. This code path has plenty of comments about Calico specific operations, so it seems that Cilium needs some work on this front.

```
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]: Waiting for access to cluster. [2021-04-11 14:04:43,340] ERROR in app: Exception on /cluster/api/v2.0/join [POST]
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]: Traceback (most recent call last):
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     response = self.full_dispatch_request()
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     rv = self.handle_user_exception(e)
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     reraise(exc_type, exc_value, tb)
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     raise value
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     rv = self.dispatch_request()
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/lib/python3.5/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/scripts/cluster/agent.py", line 594, in join_node_dqlite
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     try_initialise_cni_autodetect_for_clustering(node_addr, apply_cni=True)
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/scripts/cluster/common/utils.py", line 240, in try_initialise_cni_autodetect_for_clustering
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     if cni_is_patched():
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:   File "/snap/microk8s/2094/scripts/cluster/common/utils.py", line 207, in cni_is_patched
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]:     with open(yaml) as f:
Apr 11 14:04:43 wanted-wolf microk8s.daemon-cluster-agent[1598267]: FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/2094/args/cni-network/cni.yaml'
```

Tested with the microk8s snap package from `1.20/stable` channel:
```
snap-id:      EaXqgt1lyCaxKaQCU349mlodBkDCXRcg
tracking:     1.20/stable
refresh-date: yesterday at 21:33 UTC
channels:
  1.20/stable:      v1.20.5  2021-04-02 (2094) 218MB classic
```

**Comment by ktsakalozos** [comment]
Thank you for reporting this @ressu . The cilium addon is not suited for multi-node clusters. However we should not fail in such an ugly way. We should be warning the user and fail gracefully.

**Comment by Jorgeewa** [comment]
Hi @ktsakalozos I want to fix this problem as a first time contributor. I want to add this piece of code to utils.py however I am not sure if I am able to access a configuration object to check if cilium is enabled and/or if this error is only caused by cilium being enabled.

`def cni_is_patched():
    """
    Detect if the cni.yaml manifest already has the hint for detecting nodes routing paths
    :return: True if calico knows where the rest of the nodes are.
    """
    yaml = "{}/args/cni-network/cni.yaml".format(os.environ.get("SNAP_DATA"))
    try:
        with open(yaml) as f:
            if "can-reach" in f.read():
                return True
            else:
                return False
    except IOError as err:
        print("File not found. Error message is {err}")
        warnings.warn("Cilium add on may be enabled and this does not port well with multi node clusters")`

**Comment by ktsakalozos** [comment]
Great news @Jorgeewa the way to check if cilium is enabled is to query kubernetes for the cilium pod.

How would you handle joining nodes running different CNI plugins, ie try to join a node with calico with a node with cilium?

1.

**Comment by Jorgeewa** [comment]
Hi @ktsakalozos thanks for the quick response. So I have a couple of questions...
1) I have dug into the project and in the status.py I see two functions that fetch enabled addons-> get_status and finally is_enabled however without knowing the function specifications I can't use it.
2) I rather prefer not to ask(except when totally stuck) and edit the program with some print statements to see what it is doing especially in the above functions. I can see addon is an object that has a field check_status which I would then think is a boolean but it apparently isn't. Is there a way to do this?

Pardon my ignorance. I write python code but I want to go to the next level by contributing and have people review my code and give heads up when I am stomped.

As to your question, I am not totally sure I understand but from the issue and your comment it seems that cilium is not suitable for multi nodes and I intend to raise a warning if any of the nodes has cilium and fail gracefully.

**Comment by Jorgeewa** [comment]
Hi @ktsakalozos so I have managed to answer my own questions. I have been able to play around with the code and have a better understanding of what is happening and can also query kubectl.

`def is_enabled_addon(addon):
    """
    This function checks if an addon is enabled.

    Parameters
    ----------
    addon: string of the addon name

    Returns
    ----------
    boolean
    """
    kubeconfig = "--kubeconfig=" + os.path.expandvars("${SNAP_DATA}/credentials/client.config")
    kube_output = run("kubectl", kubeconfig, "get", "all", "--all-namespaces")
    cluster_output = run("kubectl", kubeconfig, "get", "clusterroles", "--all-namespaces")
    kube_output = kube_output + cluster_output

    for row in kube_output.split("\n"):
        isAddon = False
        if addon in row:
            isAddon = True
            break
    return isAddon`

My idea is to add the above code to check if cilium or any problematic addon is enbled before join and warn the user then let it fail silently. This code lives inside cluster utility. What do you think about it? I can create a pull request if you think it is ok.
