### ISSUE TITLE
Keep getting error dialing backend: connection refused

### ISSUE THREAD

**Issue by scythx** [ubuntu/microk8s#2222]
Hello, i have a fresh install of microk8s `1.20/stable` running on `Debian 4.19.181-1 (2021-03-19) x86_64`

```
Name         Version    Rev    Tracking       Publisher   Notes
core         16-2.49.2  10958  latest/stable  canonical✓  core
core18       20210309   1997   latest/stable  canonical✓  base
microk8s     v1.20.6    2143   1.20/stable    canonical✓  classic
```

The problem is, i keep getting dialing backend: connection refused. For example:
```sh
$ microk8s kubectl get all --all-namespaces

NAMESPACE     NAME                                             READY   STATUS    RESTARTS   AGE
kube-system   pod/dashboard-metrics-scraper-6c4568dc68-j8ksj   1/1     Running   1          5m18s
kube-system   pod/metrics-server-8bbfb4bdb-k8v9m               1/1     Running   1          5m21s
kube-system   pod/kubernetes-dashboard-7ffd448895-ppb2s        1/1     Running   1          5m18s
kube-system   pod/calico-node-rck94                            1/1     Running   1          21m
kube-system   pod/calico-kube-controllers-847c8c99d-8x42g      1/1     Running   1          21m
kube-system   pod/coredns-86f78bb79c-bxw6m                     1/1     Running   1          5m16s

NAMESPACE     NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP                  21m
kube-system   service/metrics-server              ClusterIP   10.152.183.33    <none>        443/TCP                  5m21s
kube-system   service/kubernetes-dashboard        ClusterIP   10.152.183.165   <none>        443/TCP                  5m18s
kube-system   service/dashboard-metrics-scraper   ClusterIP   10.152.183.57    <none>        8000/TCP                 5m18s
kube-system   service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   5m16s

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node   1         1         1       1            1           kubernetes.io/os=linux   21m

NAMESPACE     NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/dashboard-metrics-scraper   1/1     1            1           5m18s
kube-system   deployment.apps/metrics-server              1/1     1            1           5m21s
kube-system   deployment.apps/kubernetes-dashboard        1/1     1            1           5m18s
kube-system   deployment.apps/calico-kube-controllers     1/1     1            1           21m
kube-system   deployment.apps/coredns                     1/1     1            1           5m17s

NAMESPACE     NAME                                                   DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/dashboard-metrics-scraper-6c4568dc68   1         1         1       5m18s
kube-system   replicaset.apps/metrics-server-8bbfb4bdb               1         1         1       5m21s
kube-system   replicaset.apps/kubernetes-dashboard-7ffd448895        1         1         1       5m18s
kube-system   replicaset.apps/calico-kube-controllers-847c8c99d      1         1         1       21m
kube-system   replicaset.apps/coredns-86f78bb79c                     1         1         1       5m17s


$ microk8s dashboard-proxy

Checking if Dashboard is running.
Dashboard will be available at https://127.0.0.1:10443
Use the following token to login:
eyJhbGciOiJSUzI1NiIsImtpZCI6Im8yRUpFbExteUZNcDhZd0QxRFNWQlBVUkNqenA3OWFjMTBib0FNZjU2NHcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTl0dmx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxNzliMGJiMy0yZGUwLTRlMzYtYTMxMi02OWNkMTU0YzAyNDYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.R4WyZDvmm-Xej0xfM1b8jnOlDNVUynSBMIPxgH2cFpQClf4j0bFtexhzXgw6Tu52rlFx2lPcCTBRnvRWKeUHjZyIafhP6zRbi16Qieh5G1hbAOY5uBFB8g4_RR94O4tz4tyCOKiZU1J9n0NsAPeMgZ5_O3rc6Vcpju8cDvf4xB14GxnyKlLPLTn6EuRVQx6VR3c062r0BFVBtHXsDMzbewBLtIXoAii8BTKV8PEr90uctqgT0B5UDLm-FIHAWdqtr_DhwwD6JxRkZHCnfAle_dgO2iMuw7UDumnmiP-9n_vFSOj5HFfInZYgaMEetBClFkXfqbYWyDUeSIzkWq37Nw
error: error upgrading connection: error dialing backend: dial tcp 103.209.131.55:10250: connect: connection refused
Traceback (most recent call last):
  File "/snap/microk8s/2143/scripts/wrappers/dashboard-proxy.py", line 80, in <module>
    dashboard_proxy()
  File "/snap/microk8s/2143/scripts/wrappers/dashboard-proxy.py", line 74, in dashboard_proxy
    check_output(command)
  File "/snap/microk8s/2143/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/snap/microk8s/2143/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/current/microk8s-kubectl.wrapper', 'port-forward', '-n', 'kube-system', 'service/kubernetes-dashboard', '10443:443', '--address', '0.0.0.0']' returned non-zero exit status 1


$ microk8s.kubectl logs kubernetes-dashboard-7ffd448895-ppb2s -n kube-system

Error from server: Get "https://sql.jtk.polban.ac.id:10250/containerLogs/kube-system/kubernetes-dashboard-7ffd448895-ppb2s/kubernetes-dashboard": dial tcp 103.209.131.55:10250: connect: connection refused
```

Even though the port `10250` is up:

```sh
$ sudo netstat -tulpn

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      573/kube-proxy      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      438/sshd            
tcp        0      0 127.0.0.1:19001         0.0.0.0:*               LISTEN      475/kube-apiserver  
tcp        0      0 127.0.0.1:1338          0.0.0.0:*               LISTEN      495/containerd      
tcp        0      0 127.0.0.1:38625         0.0.0.0:*               LISTEN      495/containerd      
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      566/kubelet         
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               LISTEN      721/python3         
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      573/kube-proxy      
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN      3435/calico-node    
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      591/kube-scheduler  
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      521/kube-controller 
tcp6       0      0 :::10255                :::*                    LISTEN      566/kubelet         
tcp6       0      0 :::10257                :::*                    LISTEN      521/kube-controller 
tcp6       0      0 :::10259                :::*                    LISTEN      591/kube-scheduler  
tcp6       0      0 :::22                   :::*                    LISTEN      438/sshd            
tcp6       0      0 :::16443                :::*                    LISTEN      475/kube-apiserver  
tcp6       0      0 :::10250                :::*                    LISTEN      566/kubelet         
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -           
```

Here's the inspection log: [inspection-report-20210430_202150.tar.gz](https://github.com/ubuntu/microk8s/files/6408571/inspection-report-20210430_202150.tar.gz)

I've tried to run `1.21/stable` but `microk8s status --wait-ready` takes forever to start. So `1.20/stable` is the least broken for me since i can still deploy something.

Any help appreciated.

**Comment by balchua** [comment]
I see this in the cluster dump.

```
: "Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 103.28.12.13 103.28.14.15 2001:4860:4860::8888",
```
Does this ring a bell?

**Comment by scythx** [comment]
No it's not, i just commented one of the entry like this

```
nameserver 103.28.12.13
nameserver 103.28.14.15
nameserver 2001:4860:4860::8888
# nameserver 2001:4860:4860::8844
```

The problem still persist. And without i commented it explicitly, according to the message the content is already trimmed.

**Comment by balchua** [comment]
I didn't notice this on my cluster, but then i also disabled my ipv6.

**Comment by scythx** [comment]
How did you disable ipv6? I've tried to disable it but kubelet keep listening on tcp6 :::10250.

**Comment by balchua** [comment]
@scythx i remember simply googling it and then rebooted my laptop.  As i always stop microk8s first before shutting down.

**Comment by scythx** [comment]
Ok, turns out `127.0.0.1 psql.jtk.polban.ac.id` wasn't in `/etc/hosts`. Adding it resolve the issue. Thank you.

**Comment by balchua** [comment]
Good catch @scythx !! Thanks for updating the issue!
