### ISSUE TITLE
Microk8s installation on Azure VM not working, same script works on local Multipass VM

### ISSUE THREAD

**Issue by mdrakiburrahman** [ubuntu/microk8s#2337]
## Context/Use Case
I am trying to get a Microk8s single-node K8s cluster - that is hosted on an Azure Ubuntu 18.04 LTS VM - onboarded to [Azure Arc](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/validation-program).

I'm running into an interesting issue, where Microk8s works fine in onboarding to Arc on a _Multipass 18.04 LTS VM_ (details below) - but exact the same script isn't working on an  _Azure 18.04 LTS VM_. 

I suspect this has something to do with the Azure-specific networking and Microk8s not getting along together - I'd appreciate your expertise of Microk8s if there's any setting I could tweak to get this working on Azure. The closest issue to mine I could find was [this one](https://github.com/ubuntu/microk8s/issues/140) - I tried the steps in that article @ktsakalozos recommended - but the issue remains the same.

## Issue Details - Microk8s on Azure VM

I developed [this simple script](https://github.com/mdrakiburrahman/azure_arc/blob/93c873b613b32f9e2532053c9a8e178559327dde/azure_arc_data_jumpstart/microk8s/azure/arm_template/dc_vanilla/scripts/install_microk8s.sh#L52) that installs Microk8s on an Azure VM upon launch (Standard D8s v3 - 8 CPU, 32 GiB memory) with Ubuntu 18.04 LTS. 

Relevant bits:
```bash
sudo snap install microk8s --classic --channel=1.21/stable # ran into same issue trying with 1.17 - 1.20
sudo microk8s enable storage dns ingress helm3 dashboard
```

When onboarding the Microk8s Cluster within the Azure VM to Arc ([PowerShel Script - FYI](https://github.com/mdrakiburrahman/azure_arc/blob/93c873b613b32f9e2532053c9a8e178559327dde/azure_arc_data_jumpstart/microk8s/azure/arm_template/dc_vanilla/scripts/DataServicesLogonScript.ps1#L61)), I'm running into an error inside one of the Arc onboarding Containers that reaches out to `guestnotificationservice.azure.com:443`- where it's failing to reach out to this [onboarding endpoint](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/cluster-connect#prerequisites):
![image](https://user-images.githubusercontent.com/46581776/121820946-829ba880-cc63-11eb-8776-9e8f8300f3f0.png)

Here is the error from the container logs - same as the screenshot above:
```text
in /home/vsts/work/1/s/gopath/src/github.com/Azure/ClusterConfigurationAgent/ConnectedProxyAgent/ServiceCaller/NotificationServiceCaller.cs:line 46\n   at ConnectedProxyAgent.Program.Main(String[] args) in /home/vsts/work/1/s/gopath/src/github.com/Azure/ClusterConfigurationAgent/ConnectedProxyAgent/ConnectedProxyAgent/Program.cs:line 70 }","AgentVersion":"1.2.0","AgentTimestamp":"06/13/2021 20:19:21"}
Unhandled exception. System.Net.Http.HttpRequestException: Resource temporarily unavailable (guestnotificationservice.azure.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)

````
## Further investigation
1. The same exact [Microk8s install script](https://github.com/mdrakiburrahman/azure_arc/blob/93c873b613b32f9e2532053c9a8e178559327dde/azure_arc_data_jumpstart/microk8s/azure/arm_template/dc_vanilla/scripts/install_microk8s.sh#L52) on a local Multipass VM (18.04 LTS) works perfectly fine at the above step (Container able to reach out to  `guestnotificationservice.azure.com:443` and finish the rest of Azure Arc stuff):
![image](https://user-images.githubusercontent.com/46581776/121821064-73692a80-cc64-11eb-8ddf-50c5da094463.png)

2. On the Azure VM - instead of installing Microk8s from snap (as above), when I replaced with installing Kubeadm inside the Azure VM instead - it worked fine - [Kubeadm install script here - FYI](https://raw.githubusercontent.com/mdrakiburrahman/kubeadm-multipass/main/CreateSingleNodeCluster.sh)

3. Tried Microk8s 1.17 - 1.20 as well - same issue.

The above 3 points tell me that there's something specific to running Microk8s on Azure that's causing this issue when reaching out to the endpoint. 

## `microk8s inspect` Tarball
Microk8s Tarball from Azure VM 
[Azure-VM-inspection-report-20210613_203118.tar.gz](https://github.com/ubuntu/microk8s/files/6644594/Azure-VM-inspection-report-20210613_203118.tar.gz)

**Comment by mdrakiburrahman** [comment]
Resolved the issue - it had to do with `core-dns` pointing to Google's DNS (even after using `sudo microk8s enable dns:168.63.129.16`). As a result, my Arc container above wasn't able to resolve the necessary endpoints like `guestnotificationservice.azure.com`.

For anyone else that runs into this, here's the script I used to install Microk8s on an Azure 18.04 LTS VM:
```bash
# Sync packages
sudo apt-get update

# Installing snap
sudo apt install snapd

# Installing microk8s from specific snap channel
sudo snap install microk8s --classic --channel=1.18/stable

# Use kubectl from microk8s
sudo snap alias microk8s.kubectl kubectl

# Enable microk8s features
sudo microk8s status --wait-ready
sudo microk8s enable dns storage dashboard

# Wait until Microk8s features are done enabling
sleep 10

# Disable internal ubuntu firewall
sudo ufw disable

# See: https://stackoverflow.com/questions/66759153/how-to-access-hosts-in-my-network-from-microk8s-deployment-pods
sudo bash -c 'echo "--resolv-conf=/run/systemd/resolve/resolv.conf" >> /var/snap/microk8s/current/args/kubelet'
sudo service snap.microk8s.daemon-kubelet restart

# Update Core DNS ConfigMap to leverage Azure's DNS rather than Google's
sudo kubectl get configmap -n kube-system coredns -o yaml > coredns.yaml
sudo sed -i 's/forward . 8.8.8.8 8.8.4.4/forward . 168.63.129.16/' coredns.yaml
sudo kubectl apply -f coredns.yaml
```
