### ISSUE TITLE
subprocess.CalledProcessError exit status 1 when calling kubectl

### ISSUE THREAD

**Issue by filiphagan** [ubuntu/microk8s#2502]
First run was working fine. After rebooting when I try to execute `microk8s.enable dns dashboard storage` or `microk8s.enable kubeflow` I get an error:
```
Traceback (most recent call last):
  File "/snap/microk8s/2346/scripts/wrappers/enable.py", line 43, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/2346/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/2346/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/2346/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/2346/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/2346/scripts/wrappers/enable.py", line 36, in enable
    enabled_addons, _ = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/2346/scripts/wrappers/status.py", line 157, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2346/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2346/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/2346/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/2346/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1.
```

Issue is also mentioned here but without any solution. OP mentioned that on version 1.21 it's working fine but I'm using more recent v1.21.3 https://discuss.kubernetes.io/t/error-while-enabling-dns-and-storage/15605

OS: Ubuntu 20.04
[inspection-report-20210806_095818.tar.gz](https://github.com/ubuntu/microk8s/files/6944071/inspection-report-20210806_095818.tar.gz)

**Comment by ktsakalozos** [comment]
Could you please attach a `microk8s.inspect` tarball? I think the API server is not coming up and I need the logs from the inspection report to see why.

**Comment by filiphagan** [comment]
@ktsakalozos Hi, it's attached. The link is at the bottom of the post

**Comment by ktsakalozos** [comment]
The error I see is: `Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2021-08-06T09:58:16+02:00 is before 2021-08-06T09:42:42Z`

Is the time inside the VM correct?

**Comment by filiphagan** [comment]
Thanks for taking the time for checking this. I can't verify that, I switched to MiniKF
