### ISSUE TITLE
dial tcp: lookup <node-name>: device or resource busy

### ISSUE THREAD

**Issue by koktlzz** [ubuntu/microk8s#2557]
## Version

I installed microk8s v1.21.4/stable with CentOS 7.9 and just enabled the dns addons.

```shell
[root@gwr-microk8s ~]# snap list
Name      Version   Rev    Tracking       Publisher   Notes
core18    20210722  2128   latest/stable  canonical✓  base
microk8s  v1.21.4   2407   1.21/stable    canonical✓  classic
snapd     2.51.4    12883  latest/stable  canonical✓  snapd
[root@gwr-microk8s ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

There are there pods running in the whole cluster :

```shell
[root@gwr-microk8s ~]# microk8s.kubectl get pods --all-namespaces 
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-node-q8zrl                         1/1     Running   0          107m
kube-system   calico-kube-controllers-f7868dd95-c86b5   1/1     Running   0          107m
kube-system   coredns-7f9c69c78c-jpmpr                  1/1     Running   0          98m
```

## Issue

But if I used `kubectl logs` to watch the logs of any pods, it returned errors:
```shell
[root@gwr-microk8s ~]# microk8s.kubectl logs calico-node-q8zrl -n kube-system
Error from server: Get "https://gwr-microk8s:10250/containerLogs/kube-system/calico-node-q8zrl/calico-node": dial tcp: lookup gwr-microk8s: device or resource busy
```

And i can find some similar error message in the kubelite logs:

```shell
Sep 06 01:50:32 gwr-microk8s microk8s.daemon-kubelite[15850]: I0906 01:50:32.217634   15850 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 06 01:50:42 gwr-microk8s microk8s.daemon-kubelite[15850]: E0906 01:50:42.705463   15850 status.go:71] apiserver received an error that is not an metav1.Status: &url.Error{Op:"Get", URL:"https://gwr-microk8s:10250/containerLogs/kube-system/calico-node-q8zrl/calico-node", Err:(*net.OpError)(0xc007720870)}: Get "https://gwr-microk8s:10250/containerLogs/kube-system/calico-node-q8zrl/calico-node": dial tcp: lookup gwr-microk8s: device or resource busy
Sep 06 01:50:56 gwr-microk8s microk8s.daemon-kubelite[15850]: I0906 01:50:56.603567   15850 clientconn.go:897] blockingPicker: the picked transport is not ready, loop back to repick
```

Here is the output of  `microk8s inspect`:
```shell
[root@gwr-microk8s ~]# microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2407/inspection-report-20210906_033441.tar.gz
```

And here is the [report tarball](https://github.com/ubuntu/microk8s/files/7114131/inspection-report-20210906_033441.tar.gz).

**Comment by koktlzz** [comment]
After i enabled the dashboard addons, the same error occured in the output of `microk8s.dashboard-proxy`:
```shell
[root@gwr-microk8s ~]# microk8s.dashboard-proxy 
Checking if Dashboard is running.
Dashboard will be available at https://127.0.0.1:10443
Use the following token to login:
error: error upgrading connection: error dialing backend: dial tcp: lookup gwr-microk8s: device or resource busy
Traceback (most recent call last):
  File "/snap/microk8s/2407/scripts/wrappers/dashboard-proxy.py", line 80, in <module>
    dashboard_proxy()
  File "/snap/microk8s/2407/scripts/wrappers/dashboard-proxy.py", line 74, in dashboard_proxy
    check_output(command)
  File "/snap/microk8s/2407/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/snap/microk8s/2407/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/current/microk8s-kubectl.wrapper', 'port-forward', '-n', 'kube-system', 'service/kubernetes-dashboard', '10443:443', '--address', '0.0.0.0']' returned non-zero exit status 1.
```

**Comment by balchua** [comment]
With regards to the kubectl log error, the name `gwr-microk8s` should be resolvable.  Try adding `gwr-microk8s` to your `/etc/host`.

We recently added this issue to the docs.
https://microk8s.io/docs/troubleshooting#heading--common-issues. Under the section "io-timeout"

**Comment by koktlzz** [comment]
> With regards to the kubectl log error, the name `gwr-microk8s` should be resolvable. Try adding `gwr-microk8s` to your `/etc/host`.
> 
> We recently added this issue to the docs.
> https://microk8s.io/docs/troubleshooting#heading--common-issues. Under the section "io-timeout"

Thanks for your reply! It works for me. 
But i still confuse that `gwr-microk8s` is my node hostname and should be correctly resolved without configuring `/etc/hosts` file.

```shell
[root@gwr-microk8s ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
[root@gwr-microk8s ~]# ping gwr-microk8s
PING gwr-microk8s (10.122.70.76) 56(84) bytes of data.
64 bytes from gwr-microk8s (10.122.70.76): icmp_seq=1 ttl=64 time=0.077 ms
64 bytes from gwr-microk8s (10.122.70.76): icmp_seq=2 ttl=64 time=0.041 ms
64 bytes from gwr-microk8s (10.122.70.76): icmp_seq=3 ttl=64 time=0.062 ms
```

Why the microk8s cannot resolve my hostname? Why must specify the hostname and IP in the `/etc/hosts` file?

**Comment by koktlzz** [comment]
> With regards to the kubectl log error, the name `gwr-microk8s` should be resolvable. Try adding `gwr-microk8s` to your `/etc/host`.
> 
> We recently added this issue to the docs.
> https://microk8s.io/docs/troubleshooting#heading--common-issues. Under the section "io-timeout"

Thanks for your reply! It works for me.
