### ISSUE TITLE
ml-pipeline-ui not bundled with kubeflow?

### ISSUE THREAD

**Issue by odellus** [ubuntu/microk8s#2658]
So I successfully enabled kubeflow with microk8s and apparently the ml-pipeline-ui either doesn't come installed by default with the kubeflow add-on or it somehow failed to start because when I run `kubectl get service --all-namespaces | grep ml-pipeline` all I see is the ml-pipeline service, no ml-pipeline-ui. I'm trying to connect the kfp Python SDK client to the pipeline service, but the Python SDK wants the ml-pipeline-ui service.

So should I try to get this service running and configured myself? Any help would be greatly appreciated.
[inspection-report-20211014_231459.tar.gz](https://github.com/ubuntu/microk8s/files/7350649/inspection-report-20211014_231459.tar.gz)

**Comment by odellus** [comment]
New steps are leading to a different error when trying to connect to the ml-pipeline client with `kfp` python module.

### New steps
```bash
sudo snap install microk8s --classic --channel=1.21/stable
microk8s enable dashboard dns storage gpu metallb:10.64.140.43-10.64.140.49
# Seems to like having this step done before enabling kubeflow
microk8s config > ~/.kube/config
microk8s enable kubeflow
# I want to be able to use jupyter with kubeflow (though GPU isn't currently detected)
microk8s.juju refresh jupyter-ui --revision 10
```
### New Error
Installing and testing kfp is the same.
```bash
python3 -m pip install kfp
python3 -c "import kfp;client = kfp.Client()"
```
But the error is new and different.
```python
ERROR:root:Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp/_client.py", line 410, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 63, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api/healthz_service_api.py", line 134, in get_healthz_with_http_info
    return self.api_client.call_api(
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 188, in __call_api
    raise e
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/api_client.py", line 389, in request
    return self.rest_client.GET(url,
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 230, in GET
    return self.request("GET", url,
  File "/home/thomas/.local/lib/python3.8/site-packages/kfp_server_api/rest.py", line 224, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Mon, 18 Oct 2021 23:47:41 GMT', 'Content-Length': '173'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"ml-pipeline\"","reason":"ServiceUnavailable","code":503}
```
It repeats this message four more times before failing.

New inspection report to go along with the new install steps and the new error. Any help is much appreciated. Thank you!
[inspection-report-20211018_195547.tar.gz](https://github.com/ubuntu/microk8s/files/7369194/inspection-report-20211018_195547.tar.gz)

**Comment by odellus** [comment]
### Update
Reading through [this](https://www.kubeflow.org/docs/components/pipelines/sdk/connect-api/) documentation on connecting a kfp client to the kfp-api, I tried to set up port forwarding as they prescribe, but to the pod running the kfp-api.

By going through [the code](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.kubeflow.sh#L324) that runs with `microk8s enable kubeflow` I was able to figure out that `ml-pipeline` is a service that exposes the ports 8887 and 8888 for grpc and http connections for the `kfp-api` deployment.


```bash
# Find the pod name that corresponds to the kfp-api
pod=$(kubectl get pods -n kubeflow -o wide | grep "kfp-api-[^o]" | cut -f1 -d ' ' -)
# Verify that port 8888 is open.
port=$(kubectl get pod $pod -n kubeflow --template='{{(index (index .spec.containers 0).ports 0).containerPort}}{{"\n"}}')
# Use that pod name to set up port forwarding.
kubectl port-forward $pod 3000:$port -n kubeflow
```

opening up a new terminal and starting entering the following into the IPython REPL
```python
import kfp
client = kfp.Client(host='http://localhost:3000')
```
yields no errors. Not sure if this should be touched upon in the microk8s kubeflow addon documentation in a similar fashion to the way it would be nice to know `microk8s.juju refresh jupyter-ui --revision 10` is needed to enable the jupyter server in kubeflow would be great. Haven't tested it past connecting to the client, but that was my acceptance criteria for getting this issue resolved so I'm closing.
