### ISSUE TITLE
Trouble connecting to Kube API server

### ISSUE THREAD

**Issue by jbhf** [ubuntu/microk8s#2678]
### Issues I'm facing:
Was testing out RBAC, enabled the addon, made some changes in known_tokens.csv (but only added, I didn't remove any pre existing ones) in attempts to get external access to the Kubernetes API from my local network outside the VM , updated the VM and restarted because it was acting sluggish when I did `microk8s stop`  `microk8s start` . Restarted and now I'm receiving `The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?` . I didn't change anything in the kubectl config so that should be ok, and didn't change anything in /var/snap/microk8s/current/args/kube-apiserver  .  If I do ps aux | grep microk8s it looks like microk8s is running in the background but actively refusing my connection. If I attempt to disable RBAC with `microk8s disable RBAC` I receive the following error: 

### The error
`Traceback (most recent call last):
  File "/snap/microk8s/2488/scripts/wrappers/disable.py", line 43, in <module>
    disable(prog_name="microk8s disable")
  File "/snap/microk8s/2488/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/2488/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/2488/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/2488/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/2488/scripts/wrappers/disable.py", line 36, in disable
    _, disabled_addons = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/2488/scripts/wrappers/status.py", line 157, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2488/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2488/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/2488/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/2488/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1.`

### Details
I'm running:
Ubuntu 20.04.3 LTS
kubectl Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.2-3+a4bd0397e1cb5e", GitCommit:"a4bd0397e1cb5e638a6a6464f759114ee2250ea1", GitTreeState:"clean", BuildDate:"2021-09-16T00:05:14Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

I apologize if this is something RBAC user error related on my part, but figured if its spitting out a stack trace it might not be expected behavior.

[inspection-report-20211022_140152.tar.gz](https://github.com/ubuntu/microk8s/files/7398188/inspection-report-20211022_140152.tar.gz)
.

**Comment by balchua** [comment]
@jbhf the token file follows what's required by kubernetes static token file.

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-token-file
