### ISSUE TITLE
coredns and calico-kube-controller stuck in ContainerCreating: Failed to create pod sandbox failed to setup network for sandbox operation not supported

### ISSUE THREAD

**Issue by installe** [ubuntu/microk8s#2722]
I did a fresh install of microk8s on a 4-node raspberry pi 4 cluster, following the instructions on https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#6-thats-it. Also did a "microk8s enable dns". Both coredns and calico-kube-controller are stuck in ContainerCreating, and kubectl describe pod ... shows "Failed to create pod sandbox [...] failed to setup network for sandbox operation not supported. Before I did "microk8s enable dns", calico-kube-controller was also already in that state

[inspection-report-20211113_183336.tar.gz](https://github.com/ubuntu/microk8s/files/7532554/inspection-report-20211113_183336.tar.gz)
.

**Comment by installe** [comment]
On one of the nodes, I found the following in /var/log/containers/calico-node[...]kube-system_calico-node[...]. I wonder if the SEGV in the stacktrace for newNetLinkRequest is the cause for the message "failed to setup network for sandbox: operation not supported".

==========
2021-11-13T18:00:41.494527321Z stdout F goroutine 101 [running]:
2021-11-13T18:00:41.49454945Z stdout F github.com/vishvananda/netlink.(*Handle).newNetlinkRequest(...)
2021-11-13T18:00:41.494570617Z stdout F         /go/pkg/mod/github.com/vishvananda/netlink@v1.1.0/handle_linux.go:133
2021-11-13T18:00:41.494592376Z stdout F github.com/vishvananda/netlink.(*Handle).LinkList(0x0, 0x18b92f4, 0x40000b4180, 0x4000114140, 0x40001141e0, 0x3)
2021-11-13T18:00:41.494612653Z stdout F         /go/pkg/mod/github.com/vishvananda/netlink@v1.1.0/link_linux.go:1799 +0x28
2021-11-13T18:00:41.494634116Z stdout F github.com/projectcalico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x400033a500, 0x40009538c0, 0x400033a500, 0x0, 0x400033a500, 0x22323d8)
2021-11-13T18:00:41.494710319Z stdout F         /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20210514180456-c47545c56459/dataplane/linux/vxlan_mgr.go:383 +0x3c
2021-11-13T18:00:41.494737041Z stdout F github.com/projectcalico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x400033a500, 0x40009538c0, 0x1, 0x1, 0x40005fa0b0)
2021-11-13T18:00:41.494755781Z stdout F         /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20210514180456-c47545c56459/dataplane/linux/vxlan_mgr.go:203 +0x34
2021-11-13T18:00:41.494774559Z stdout F github.com/projectcalico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x400033a500, 0x5a0, 0x2540be400)
2021-11-13T18:00:41.494792947Z stdout F         /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20210514180456-c47545c56459/dataplane/linux/vxlan_mgr.go:353 +0xcc
2021-11-13T18:00:41.494811466Z stdout F created by github.com/projectcalico/felix/dataplane/linux.NewIntDataplaneDriver
2021-11-13T18:00:41.494830206Z stdout F         /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20210514180456-c47545c56459/dataplane/linux/int_dataplane.go:446 +0xd20
2021-11-13T18:00:42.936898383Z stdout F panic: runtime error: invalid memory address or nil pointer dereference
2021-11-13T18:00:42.936994011Z stdout F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124beb8]

**Comment by balchua** [comment]
Hi @installe i can see that you are using 21.10 ubuntu.

There's an extra package you need to install in the OS.  Check the documentation, where the team recently added some instructions on what to do with ubuntu impish.

https://microk8s.io/docs/troubleshooting#heading--common-issues

**Comment by installe** [comment]
Thanks @balchua, that indeed solved my issue.
