### ISSUE TITLE
HA got disabled by itself and error "symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno"

### ISSUE THREAD

**Issue by joes** [ubuntu/microk8s#2784]
I was setting up a new developer environment using multipass and a "Ubuntu 20.04.3 LTS" machine with this cloud-config:

```yaml
#cloud-config
runcmd:
 - snap install microk8s --classic --channel 1.20/stable
 - snap refresh microk8s
 - microk8s start
 - microk8s status --wait-ready
 - microk8s enable rbac dns:10.4.1.10,10.4.1.11 dashboard ingress storage registry
 - microk8s status --wait-ready
 - mkdir -vp "$HOME/.kube"
 - mkdir -vp /home/ubuntu/.kube
 - microk8s config | tee "$HOME/.kube/config" | tee /home/ubuntu/.kube/config
 - usermod -a -G microk8s $USER
 - usermod -a -G microk8s ubuntu
 - echo "chown -f -R $USER ~/.kube"
 - chown -f -R $USER ~/.kube
 - echo "chown -f -R ubuntu /home/ubuntu/.kube"
 - chown -f -R ubuntu /home/ubuntu/.kube
final_message: "The system is finally up, after $UPTIME seconds"
```

```shell
"/mnt/c/Program Files/Multipass/bin/multipass.exe" launch -v --cpus 2 --mem 8G --name "$k8_node_name" focal --cloud-init "cloud-init.yaml"
```

I then ran `microk8s status` on the newly created machine and got some error messages related to dqlite:

OUTPUT:

```
microk8s is running
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
^CTraceback (most recent call last):
  File "/snap/microk8s/2702/scripts/wrappers/common/utils.py", line 89, in get_dqlite_info
    timeout=4,
  File "/snap/microk8s/2702/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/snap/microk8s/2702/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/2702/bin/dqlite', '-s', 'file:///var/snap/microk8s/2702/var/kubernetes/backend/cluster.yaml', '-c', '/var/snap/microk8s/2702/var/kubernetes/backend/cluster.crt', '-k', '/var/snap/microk8s/2702/var/kubernetes/backend/cluster
.key', '-f', 'json', 'k8s', '.cluster']' returned non-zero exit status 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/microk8s/2702/scripts/wrappers/status.py", line 244, in <module>
    print_pretty(isReady, enabled, disabled)
  File "/snap/microk8s/2702/scripts/wrappers/status.py", line 52, in print_pretty
    info = get_dqlite_info()
  File "/snap/microk8s/2702/scripts/wrappers/common/utils.py", line 97, in get_dqlite_info
    time.sleep(2)
KeyboardInterrupt
```

I also have a three node cluster with microk8s (tracking 1.20/stable) on "Ubuntu 20.04.3 LTS" that had HA enabled at the time the nodes were installed. The nodes were initially set up with Rev 2649 but was at some later time upgrade to revision 2702.

I checked `microk8s status` on these nodes too to see if I got the same error there:

OUTPUT

```
microk8s is running
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2702/bin/dqlite: symbol lookup error: /snap/microk8s/2702/bin/dqlite: undefined symbol: sqlite3_system_errno
high-availability: no
  datastore master nodes: none
  datastore standby nodes: none
addons:
  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    metrics-server       # K8s Metrics Server for API access to service metrics
    rbac                 # Role-Based Access Control for authorisation
    storage              # Storage class; allocates storage from host directory
```

Much to my dismay that was the case and, moreover, HA is now disabled (due to dqlite not functioning?)

The Kubernetes API seems to work and the "Kubernetes Dashboard" shows no errors related to the workloads on these nodes. 

Can this cluster be healed in some way or is it time to reinstall everything? 

I have tried to do refresh the snap and restart the node but the error persists.

**Comment by ktsakalozos** [comment]
Hi @joes,

Thank you for bringing this to our attention. We are working on it and we should have news soon.

**Comment by ktsakalozos** [comment]
@joes, can you try to refresh to 1.20/edge channel? The issue seems to be with the way the Launchpad builders build the MicroK8s snap.

**Comment by joes** [comment]
Tried on one of the nodes and am seeing these error messages there (journalctl):

**Comment by joes** [comment]
It seemed to do the trick - no more symbol lookup errors errors and HA seems to be detected. But how can I know for sure that HA is functional after the refresh? I mean, could there be any lingering effects by the HA disruption?

```
microk8s is running
high-availability: yes
  datastore master nodes: 10.10.11.101:19001 10.10.11.28:19001 10.10.11.110:19001
  datastore standby nodes: none
```
