### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by forging2012** [ubuntu/microk8s#2834]
```
MacOS: 10.15.7
➜  ~ python -V
Python 3.10.1
➜  ~ microk8s kubectl get all --all-namespaces
An unexpected error occurred.
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/local/Cellar/microk8s/2.2.0/libexec/lib/python3.9/site-packages/cli/microk8s.py", line 55, in cli
    exit(kubectl(ctx.args[1:]))
  File "/usr/local/Cellar/microk8s/2.2.0/libexec/lib/python3.9/site-packages/cli/microk8s.py", line 209, in kubectl
    return MacOS(args).kubectl()
  File "/usr/local/Cellar/microk8s/2.2.0/libexec/lib/python3.9/site-packages/common/auxiliary.py", line 76, in kubectl
    kctl_dir = self.get_kubectl_directory()
  File "/usr/local/Cellar/microk8s/2.2.0/libexec/lib/python3.9/site-packages/common/auxiliary.py", line 57, in get_kubectl_directory
    return get_kubectl_directory()
  File "/usr/local/Cellar/microk8s/2.2.0/libexec/lib/python3.9/site-packages/common/file_utils.py", line 77, in get_kubectl_directory
    return os.path.dirname(full_path)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
None

```

```
➜  ~ microk8s inspect          
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2695/inspection-report-20220112_101605.tar.gz
```

**Comment by neoaggelos** [comment]
Hi @forging2012, thank you for filing this issue.

The error basically means that the `microk8s kubectl` command failed to resolve the path to the kubectl binary on your system. A more helpful error message would definitely help here, and we can certainly improve that.

However, that should not happen. Did you follow [the docs](https://microk8s.io/docs/install-alternatives#heading--macos) to install MicroK8s? The `brew install ubuntu/microk8s/microk8s` command should also install `kubectl` for you.

Is `kubectl` present on your system? What's the output of `which kubectl`?

**Comment by forging2012** [comment]
I reinstall python, then solved the problem.
```
brew install python@3.9
```
Thank you!
