### ISSUE TITLE
Joining Nodes Fails

### ISSUE THREAD

**Issue by VonRehberg** [ubuntu/microk8s#978]
Currently we're unable to join two nodes.
I guess the reason is, that the signing process fails due to unavailable openssl conf in the agent.py of the to-be master node.

As you can see in utils.sh, the openssl_conf environment variable is set:
https://github.com/ubuntu/microk8s/blob/1ce4147d637a8628fafa9707e2e7b72dfa21b44b/microk8s-resources/actions/common/utils.sh#L306

However, in the agent.py this is not the case:
https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/agent.py

This leads to the following error when tailing journalctl:
```
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + export PATH=/snap/microk8s/1173/usr/sbin:/snap/microk8s/1173/usr/bin:/snap/microk8s/1173/sbin:/snap/microk8s/1173/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + PATH=/snap/microk8s/1173/usr/sbin:/snap/microk8s/1173/usr/bin:/snap/microk8s/1173/sbin:/snap/microk8s/1173/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: ++ /snap/microk8s/1173/bin/uname -m
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + ARCH=x86_64
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + export LD_LIBRARY_PATH=:/snap/microk8s/1173/lib:/snap/microk8s/1173/usr/lib:/snap/microk8s/1173/lib/x86_64-linux-gnu:/snap/microk8s/1173/usr/lib/x86_64-linux-gnu
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + LD_LIBRARY_PATH=:/snap/microk8s/1173/lib:/snap/microk8s/1173/usr/lib:/snap/microk8s/1173/lib/x86_64-linux-gnu:/snap/microk8s/1173/usr/lib/x86_64-linux-gnu
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + export LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void::/snap/microk8s/1173/lib:/snap/microk8s/1173/usr/lib:/snap/microk8s/1173/lib/x86_64-linux-gnu:/snap/microk8s/1173/usr/lib/x86_64-linux-gnu
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void::/snap/microk8s/1173/lib:/snap/microk8s/1173/usr/lib:/snap/microk8s/1173/lib/x86_64-linux-gnu:/snap/microk8s/1173/usr/lib/x86_64-linux-gnu
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + source /snap/microk8s/1173/actions/common/utils.sh
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + app=kube-apiserver
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' -e /var/snap/microk8s/1173/var/lock/clustered.lock ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' kube-apiserver = kubelet ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' kube-apiserver = kube-apiserver ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + grep -E '(--advertise-address|--bind-address)' /var/snap/microk8s/1173/args/kube-apiserver
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + rm -f /var/snap/microk8s/1173/external_ip.txt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + n=0
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' 0 -ge 20 ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + ip route
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + grep default
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + break
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' -e /var/snap/microk8s/1173/var/lock/stopped.lock ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: ++ cat /var/snap/microk8s/1173/args/kube-apiserver
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + declare -a 'args=(--cert-dir=${SNAP_DATA}/certs
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --service-cluster-ip-range=10.152.183.0/24
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --authorization-mode=AlwaysAllow
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --basic-auth-file=${SNAP_DATA}/credentials/basic_auth.csv
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --service-account-key-file=${SNAP_DATA}/certs/serviceaccount.key
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --client-ca-file=${SNAP_DATA}/certs/ca.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --tls-cert-file=${SNAP_DATA}/certs/server.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --tls-private-key-file=${SNAP_DATA}/certs/server.key
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --kubelet-client-certificate=${SNAP_DATA}/certs/server.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --kubelet-client-key=${SNAP_DATA}/certs/server.key
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --secure-port=16443
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --token-auth-file=${SNAP_DATA}/credentials/known_tokens.csv
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --etcd-servers='\''https://127.0.0.1:12379'\''
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --etcd-cafile=${SNAP_DATA}/certs/ca.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --etcd-certfile=${SNAP_DATA}/certs/server.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --etcd-keyfile=${SNAP_DATA}/certs/server.key
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --insecure-port=0
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: # Enable the aggregation layer
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --requestheader-client-ca-file=${SNAP_DATA}/certs/front-proxy-ca.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --requestheader-allowed-names=front-proxy-client
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --requestheader-extra-headers-prefix=X-Remote-Extra-
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --requestheader-group-headers=X-Remote-Group
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --requestheader-username-headers=X-Remote-User
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --proxy-client-cert-file=${SNAP_DATA}/certs/front-proxy-client.crt
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: --proxy-client-key-file=${SNAP_DATA}/certs/front-proxy-client.key
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: #~Enable the aggregation layer
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: OPENSSL_CONF=/snap/microk8s/current/etc/ssl/openssl.cnf)'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + '[' -f /snap/microk8s/1173/kube-apiserver ']'
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: + exec /snap/microk8s/1173/kube-apiserver --cert-dir=/var/snap/microk8s/1173/certs --service-cluster-ip-range=10.152.183.0/24 --authorization-mode=AlwaysAllow --basic-auth-file=/var/snap/microk8s/1173/credentials/basic_auth.csv --service-account-key-file=/var/snap/microk8s/1173/certs/serviceaccount.key --client-ca-file=/var/snap/microk8s/1173/certs/ca.crt --tls-cert-file=/var/snap/microk8s/1173/certs/server.crt --tls-private-key-file=/var/snap/microk8s/1173/certs/server.key --kubelet-client-certificate=/var/snap/microk8s/1173/certs/server.crt --kubelet-client-key=/var/snap/microk8s/1173/certs/server.key --secure-port=16443 --token-auth-file=/var/snap/microk8s/1173/credentials/known_tokens.csv --token-auth-file=/var/snap/microk8s/1173/credentials/known_tokens.csv --etcd-servers=https://127.0.0.1:12379 --etcd-cafile=/var/snap/microk8s/1173/certs/ca.crt --etcd-certfile=/var/snap/microk8s/1173/certs/server.crt --etcd-keyfile=/var/snap/microk8s/1173/certs/server.key --insecure-port=0 --requestheader-client-ca-file=/var/snap/microk8s/1173/certs/front-proxy-ca.crt --requestheader-allowed-names=front-proxy-client --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --proxy-client-cert-file=/var/snap/microk8s/1173/certs/front-proxy-client.crt --proxy-client-key-file=/var/snap/microk8s/1173/certs/front-proxy-client.key OPENSSL_CONF=/snap/microk8s/current/etc/ssl/openssl.cnf
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: Error configuring OpenSSL
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: 139654996838040:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: 139654996838040:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: 139654996838040:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:271:module=ssl_conf, path=ssl_conf
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: 139654996838040:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:212:module=ssl_conf
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: [2020-02-25 16:17:45,270] ERROR in app: Exception on /cluster/api/v1.0/sign-cert [POST]
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: Traceback (most recent call last):
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     response = self.full_dispatch_request()
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     rv = self.handle_user_exception(e)
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     reraise(exc_type, exc_value, tb)
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     raise value
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     rv = self.dispatch_request()
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     return self.view_functions[rule.endpoint](**req.view_args)
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/scripts/cluster/agent.py", line 326, in sign_cert
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     signed_cert = sign_client_cert(cert_request, token)
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/scripts/cluster/agent.py", line 112, in sign_client_cert
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     subprocess.check_call(sign_cmd.split())
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:   File "/snap/microk8s/1173/usr/lib/python3.5/subprocess.py", line 581, in check_call
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]:     raise CalledProcessError(retcode, cmd)
Feb 25 16:17:45 enigma microk8s.daemon-cluster-agent[16746]: subprocess.CalledProcessError: Command '['openssl', 'x509', '-req', '-in', '/var/snap/microk8s/1173/certs/request.MpncPmITCBoLYklcrDnGEFjdKkNKEFCr.csr', '-CA', '/var/snap/microk8s/1173/certs/ca.crt', '-CAkey', '/var/snap/microk8s/1173/certs/ca.key', '-CAcreateserial', '-out', '/var/snap/microk8s/1173/certs/server.MpncPmITCBoLYklcrDnGEFjdKkNKEFCr.crt', '-days', '100000']' returned non-zero exit status 1
Feb 25 16:17:45 enigma microk8s.daemon-apiserver[25306]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
```

On the joining node the error looks like the following, as the HTTP return code is not 200:
```
microk8s.join 192.168.178.56:25000/WRQCQhSKxTcmzOhYAYdDOqmqFSGkOmky
Traceback (most recent call last):
  File "/snap/microk8s/1174/scripts/cluster/join.py", line 397, in <module>
    update_flannel(info["etcd"], master_ip, master_port, token)
  File "/snap/microk8s/1174/scripts/cluster/join.py", line 136, in update_flannel
    get_etcd_client_cert(master_ip, master_port, token)
  File "/snap/microk8s/1174/scripts/cluster/join.py", line 119, in get_etcd_client_cert
    print("Failed to sign certificate. {}".format(signed.json()["error"]))
  File "/snap/microk8s/1174/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/snap/microk8s/1174/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/snap/microk8s/1174/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/microk8s/1174/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ktsakalozos** [comment]
Thank you for reporting and investigating this bug @VonRehberg. What system is this on (distribution)? It would help me reproduce the issue and verify the fix you are suggesting.

**Comment by VonRehberg** [comment]
Thanks for the fast reply!

```
uname -a
Linux enigma 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

**Comment by 8bitbuddhist** [comment]
This isn't the exact same error, but I'm getting a similar error on two Ubuntu Bionic machines:

```
$ microk8s.join 10.0.2.15:25000/<token>
Traceback (most recent call last):
  File "/snap/microk8s/1173/scripts/cluster/join.py", line 390, in <module>
    info = get_connection_info(master_ip, master_port, token, callback_token)
  File "/snap/microk8s/1173/scripts/cluster/join.py", line 60, in get_connection_info
    print("Failed to join cluster. {}".format(connection_info.json()["error"]))
  File "/snap/microk8s/1173/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/snap/microk8s/1173/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/snap/microk8s/1173/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/snap/microk8s/1173/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
$ uname -a
Linux microk8s-b 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ktsakalozos** [comment]
@8bitbuddhist could you attach the `microk8s.inspect` tarball created on the master node? I would like to see what the error on the cluster agent was. Thank you.

**Comment by ktsakalozos** [comment]
@VonRehberg I believe I addressed the issue. Could you also verify this by installing MicroK8s from this hotfix branch: `sudo snap install microk8s --classic --channel=edge/test-openssl-fix` ?

Thank you.

**Comment by 8bitbuddhist** [comment]
> @8bitbuddhist could you attach the `microk8s.inspect` tarball created on the master node? I would like to see what the error on the cluster agent was. Thank you.

Attached. I just tried rejoining around 2 minutes ago.
[inspection-report-20200227_140857.tar.gz](https://github.com/ubuntu/microk8s/files/4262016/inspection-report-20200227_140857.tar.gz)

**Comment by ktsakalozos** [comment]
@8bitbuddhist could you describe your setup? I see you are using a VM? Is that on a cloud? Which nodes are you trying to join? I am practically asking for a way to reproduce this error. Thank you.

**Comment by VonRehberg** [comment]
@ktsakalozos I refreshed microk8s from your hotfix branch and now it's working 👍 Thanks a lot for the quick fix!

**Comment by 8bitbuddhist** [comment]
> @8bitbuddhist could you describe your setup? I see you are using a VM? Is that on a cloud? Which nodes are you trying to join? I am practically asking for a way to reproduce this error. Thank you.

False alarm. I was using two VMs in VirtualBox, but forgot to configure the NAT network so the two machines could actually communicate. I switched to a bridged adapter and it works fine now.
