### ISSUE TITLE
etcd problem + snap refresh failure

### ISSUE THREAD

**Issue by timwebster9** [ubuntu/microk8s#984]
My apiserver all of sudden fell over after running pretty much flawlessly for about 2 months.  It looks like etcd is the problem.  Looks like something to do with the recent upgrade to 3.4?

It's a multi-node cluster on RPi 4B (Ubuntu 19.10, fully up to date).  Inspection report attached.

From the apiserver logs:

```
Feb 26 15:15:46 io microk8s.daemon-apiserver[9125]: I0226 15:15:46.842986    9125 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:12379 0  <nil>}]
Feb 26 15:15:47 io microk8s.daemon-apiserver[9125]: W0226 15:15:47.777158    9125 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:12379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:40640->127.0.0.1:12379: read: connection reset by peer". Reconnecting...
Feb 26 15:15:47 io microk8s.daemon-apiserver[9125]: W0226 15:15:47.777207    9125 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:12379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:40644->127.0.0.1:12379: read: connection reset by peer". Reconnecting...
Feb 26 15:15:50 io microk8s.daemon-apiserver[9125]: W0226 15:15:50.234521    9125 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:12379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:40650->127.0.0.1:12379: read: connection reset by peer". Reconnecting...
Feb 26 15:15:50 io microk8s.daemon-apiserver[9125]: W0226 15:15:50.235216    9125 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:12379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:40648->127.0.0.1:12379: read: connection reset by peer". Reconnecting...
```

and then the etcd logs:

```
Feb 26 15:16:04 io etcd[9798]: enabled capabilities for version 3.3
Feb 26 15:16:04 io etcd[9798]: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
Feb 26 15:16:04 io etcd[9798]: set the cluster version to 3.3 from store
Feb 26 15:16:04 io etcd[9798]: restore compact to 13963548
Feb 26 15:16:04 io etcd[9798]: simple token is not cryptographically signed
Feb 26 15:16:04 io etcd[9798]: starting server... [version: 3.3.4, cluster version: 3.3]
Feb 26 15:16:04 io etcd[9798]: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
Feb 26 15:16:04 io etcd[9798]: ClientTLS: cert = /var/snap/microk8s/1174/certs/server.crt, key = /var/snap/microk8s/1174/certs/server.key, ca = , trusted-ca = /var/snap/microk8s/1174/certs/ca.crt, client-cert-auth = true, crl-file =
Feb 26 15:16:05 io etcd[9798]: updated the cluster version from 3.3 to 3.4
Feb 26 15:16:05 io etcd[9798]: cluster cannot be downgraded (current version: 3.3.4 is lower than determined cluster version: 3.4).
Feb 26 15:16:05 io systemd[1]: snap.microk8s.daemon-etcd.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 15:16:05 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
```

[inspection-report-20200226_152214.tar.gz](https://github.com/ubuntu/microk8s/files/4257157/inspection-report-20200226_152214.tar.gz)

EDIT: also looks like the snap change failed, which occured about the time that I noticed that the cluster was down:

```
+ sudo -E /snap/microk8s/1216/usr/bin/python3 /snap/microk8s/1216/scripts/cluster/distributed_op.py remove_argument kubectl --kubeconfig
Removing argument --kubeconfig from nodes.
Applying to node triton.
Traceback (most recent call last):
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 549, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 764, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 161, in <module>
    remove_argument(service, args[2])
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 104, in remove_argument
    do_op(remote_op)
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 38, in do_op
    verify=False)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```

**Comment by balchua** [comment]
@timwebster9 thanks for reporting this.  Can you try adding this `--enable-v2=true` in the file `/var/snap/microk8s/args/etcd`?  Then restart etcd? 
There could be a bug during the snap refresh preventing the snap refresh to automatically add this argument.

**Comment by timwebster9** [comment]
OK thank you I will try that.  Any idea about the `SSL module is not available` issue with the snap refresh?

**Comment by ktsakalozos** [comment]
@timwebster9 could you share the output of `snap changes microk8s`? I would like to see what happened exactly. Right now a `snap refresh microk8s` will fail?

**Comment by ktsakalozos** [comment]
Also @timwebster9 if you intend to have long lasting deployments you would be safer if you specify a channel during your snap install eg `sudo snap install microk8s --classic --channel=1.17/stable`.

Backwards incompatible changes are introduced by the upstream Kubernetes project or by MicroK8s in the latest stable track that you are following when you do not select a specific channel. Have a look at https://microk8s.io/docs/setting-snap-channel

**Comment by timwebster9** [comment]
@ktsakalozos yes right now a snap refresh fails with the python SSL error I posted above.  I believe snap attempted 2 automatic refreshes yesterday and they both failed with the same error.   A manual `snap refresh` also failed with the same error.

I will post the full output later when I get home.

Regarding the stable channel, I think I originally just used `snap install microk8s --classic`.  I see I can change the channel so will do that as well.  Thanks!

**Comment by ktsakalozos** [comment]
I do understand how this library appears to be missing now. This should have failed at the very beginning when the cluster was formed.

Here is a workaround that should get you through the refresh process. Create the file `/var/snap/micro8s/current/args/kubectl-env` and put inside this line:
```
export KUBECONFIG=$SNAP_DATA/credentials/client.config
```
Then try to refresh.

**Comment by timwebster9** [comment]
@ktsakalozos you asked for the output of `snap changes microk8s`:

```
root@io:~# snap changes microk8s
ID   Status  Spawn                   Ready                   Summary
28   Error   yesterday at 18:10 UTC  yesterday at 18:12 UTC  Auto-refresh snap "microk8s"
29   Error   yesterday at 18:40 UTC  yesterday at 18:42 UTC  Refresh snap "microk8s"
30   Error   today at 03:08 UTC      today at 03:10 UTC      Auto-refresh snap "microk8s"
31   Error   today at 09:58 UTC      today at 10:00 UTC      Auto-refresh snap "microk8s"
32   Error   today at 17:23 UTC      today at 17:25 UTC      Refresh snap "microk8s"
33   Error   today at 17:30 UTC      today at 17:32 UTC      Refresh snap "microk8s"
34   Error   today at 17:35 UTC      today at 17:37 UTC      Refresh "microk8s" snap
```

and adding the `kubectl-env` file didn't seem to help:

```
root@io:/var/snap/microk8s/current/args# cat /var/snap/microk8s/current/args/kubectl-env
export KUBECONFIG=$SNAP_DATA/credentials/client.config

root@io:/var/snap/microk8s/current/args# snap refresh microk8s
error: cannot perform the following tasks:
- Run configure hook of "microk8s" snap if present (run hook "configure":
-----
+++ '[' 10.1.82.1 '!=' 10.1.82.1 ']'
+++ IP_ADDR=192.168.1.131
+++ echo 192.168.1.131
++ local IP_ADDRESSES=192.168.1.131
++ cp /var/snap/microk8s/1216/certs/csr.conf.template /var/snap/microk8s/1216/certs/csr.conf.rendered
++ '[' 192.168.1.131 == 127.0.0.1 ']'
++ '[' 192.168.1.131 == none ']'
++ local ips= sep=
++ local -i i=3
+++ echo 192.168.1.131
++ for IP_ADDR in $(echo "$IP_ADDRESSES")
++ ips+='IP.3 = 192.168.1.131'
++ sep='\n'
++ /snap/microk8s/1216/bin/sed -i 's/#MOREIPS/IP.3 = 192.168.1.131/g' /var/snap/microk8s/1216/certs/csr.conf.rendered
++ '[' -f /var/snap/microk8s/1216/certs/csr.conf ']'
++ local force
++ /snap/microk8s/1216/usr/bin/cmp -s /var/snap/microk8s/1216/certs/csr.conf.rendered /var/snap/microk8s/1216/certs/csr.conf
++ force=false
++ false
++ '[' '!' -f /var/snap/microk8s/1216/certs/front-proxy-client.crt ']'
+++ /snap/microk8s/1216/usr/bin/openssl x509 -noout -issuer
++ '[' 'issuer= /CN=front-proxy-ca' == 'issuer=CN = 127.0.0.1' ']'
++ echo 0
+ '[' 0 == 1 ']'
+ '[' -e /var/snap/microk8s/1216/args/containerd-template.toml ']'
+ grep -e 'stream_server_address = ""' /var/snap/microk8s/1216/args/containerd-template.toml
+ grep -e '\-\-allow-privileged' /var/snap/microk8s/1216/args/kubelet
+ '[' -f /root/snap/microk8s/common/istio-auth.lock ']'
+ '[' -f /root/snap/microk8s/common/istio-auth.lock ']'
+ need_api_restart=false
+ '[' -f /var/snap/microk8s/1216/credentials/kubelet.config ']'
+ '[' -f /var/snap/microk8s/1216/credentials/proxy.config ']'
+ '[' -f /var/snap/microk8s/1216/credentials/scheduler.config ']'
+ '[' -f /var/snap/microk8s/1216/credentials/controller.config ']'
+ for dir in "${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock"
+ chmod -R ug+rwX /var/snap/microk8s/1216/credentials/ /var/snap/microk8s/1216/certs/ /var/snap/microk8s/1216/args/ /var/snap/microk8s/1216/var/lock
+ chmod -R o-rwX /var/snap/microk8s/1216/credentials/ /var/snap/microk8s/1216/certs/ /var/snap/microk8s/1216/args/ /var/snap/microk8s/1216/var/lock
+ getent group microk8s
+ getent group microk8s
+ chgrp microk8s -R /var/snap/microk8s/1216/credentials/ /var/snap/microk8s/1216/certs/ /var/snap/microk8s/1216/args/ /var/snap/microk8s/1216/var/lock/
+ '[' -f /var/snap/microk8s/1216/args/flanneld ']'
+ grep -e etcd.socket:2379 /var/snap/microk8s/1216/args/etcd
+ grep '\-\-enable\-v2' /var/snap/microk8s/1216/args/etcd
+ refresh_opt_in_config enable-v2 true etcd
+ local opt=--enable-v2
+ local value=true
+ local config_file=/var/snap/microk8s/1216/args/etcd
+ local replace_line=--enable-v2=true
++ grep -qE '^--enable-v2=' /var/snap/microk8s/1216/args/etcd
+ run_with_sudo /snap/microk8s/1216/bin/sed -i '$ a --enable-v2=true' /var/snap/microk8s/1216/args/etcd
+ '[' -n '' ']'
+ '[' /snap/microk8s/1216/bin/sed == preserve_env ']'
+ sudo /snap/microk8s/1216/bin/sed -i '$ a --enable-v2=true' /var/snap/microk8s/1216/args/etcd
+ '[' -e /var/snap/microk8s/1216/credentials/callback-tokens.txt ']'
++ run_with_sudo /snap/microk8s/1216/bin/cat /var/snap/microk8s/1216/credentials/callback-tokens.txt
++ '[' -n '' ']'
++ '[' /snap/microk8s/1216/bin/cat == preserve_env ']'
++ sudo /snap/microk8s/1216/bin/cat /var/snap/microk8s/1216/credentials/callback-tokens.txt
++ /snap/microk8s/1216/usr/bin/wc -l
+ tokens=1
+ [[ 1 -ge 0 ]]
+ run_with_sudo preserve_env /snap/microk8s/1216/usr/bin/python3 /snap/microk8s/1216/scripts/cluster/distributed_op.py update_argument etcd --enable-v2 true
+ '[' -n '' ']'
+ '[' preserve_env == preserve_env ']'
+ shift
+ sudo -E /snap/microk8s/1216/usr/bin/python3 /snap/microk8s/1216/scripts/cluster/distributed_op.py update_argument etcd --enable-v2 true
Adding argument --enable-v2 to nodes.
Applying to node triton.
Traceback (most recent call last):
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 549, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 764, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 159, in <module>
    update_argument(service, args[2], args[3])
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 84, in update_argument
    do_op(remote_op)
  File "/snap/microk8s/1216/scripts/cluster/distributed_op.py", line 38, in do_op
    verify=False)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/snap/microk8s/1216/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
-----)
```

**Comment by timwebster9** [comment]
also this worked: `adding this --enable-v2=true in the file /var/snap/microk8s/args/etcd`.  The cluster is up and running now.

**Comment by timwebster9** [comment]
and lastly, switching to the stable channel seemed to help as well:

```
root@io~:# snap refresh microk8s --channel=1.17/stable
microk8s (1.17/stable) v1.17.2 from Canonical✓ refreshed
```

**Comment by timwebster9** [comment]
OK so I did a `sudo snap refresh microk8s --channel=1.17/stable` to switch the channel, and it failed again.  Still with the etcd problem.  With or without `--enable-v2=true` it fails with:

```
cluster cannot be downgraded (current version: 3.3.4 is lower than determined cluster version: 3.4).
```

Not sure what's going on here - what's the best way to fix this?  A reinstall?

**Comment by ktsakalozos** [comment]
Could you try refreshing again to 1.17/stable?

**Comment by timwebster9** [comment]
```
root@io:/var/snap/microk8s/current/args# snap refresh microk8s --channel=1.17/stable
microk8s (1.17/stable) v1.17.3 from Canonical✓ refreshed
```

but then:

```
root@io:/var/snap/microk8s/current/args# systemctl status snap.microk8s.daemon-etcd.service
● snap.microk8s.daemon-etcd.service - Service for snap application microk8s.daemon-etcd
   Loaded: loaded (/etc/systemd/system/snap.microk8s.daemon-etcd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-02-27 19:35:50 UTC; 1min 50s ago
  Process: 29960 ExecStart=/usr/bin/snap run microk8s.daemon-etcd (code=exited, status=1/FAILURE)
 Main PID: 29960 (code=exited, status=1/FAILURE)

Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Service RestartSec=100ms expired, scheduling restart.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Scheduled restart job, restart counter is at 6.
Feb 27 19:35:50 io systemd[1]: Stopped Service for snap application microk8s.daemon-etcd.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Start request repeated too quickly.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
Feb 27 19:35:50 io systemd[1]: Failed to start Service for snap application microk8s.daemon-etcd.
```

```
root@io:/var/snap/microk8s/current/args# journalctl --unit snap.microk8s.daemon-etcd.service
-- Logs begin at Thu 2020-02-27 18:59:11 UTC, end at Thu 2020-02-27 19:38:00 UTC. --
Feb 27 19:35:35 io systemd[1]: Started Service for snap application microk8s.daemon-etcd.
Feb 27 19:35:39 io etcd[29184]: running etcd on unsupported architecture "arm64" since ETCD_UNSUPPORTED_ARCH is set
Feb 27 19:35:39 io etcd[29184]: etcd Version: 3.3.4
Feb 27 19:35:39 io etcd[29184]: Git SHA: fdde8705f
Feb 27 19:35:39 io etcd[29184]: Go Version: go1.9.5
Feb 27 19:35:39 io etcd[29184]: Go OS/Arch: linux/arm64
Feb 27 19:35:39 io etcd[29184]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Feb 27 19:35:39 io etcd[29184]: the server is already initialized as member before, starting as etcd member...
Feb 27 19:35:40 io etcd[29184]: listening for peers on http://localhost:2380
Feb 27 19:35:40 io etcd[29184]: listening for client requests on 0.0.0.0:12379
Feb 27 19:35:40 io etcd[29184]: recovered store from snapshot at index 27506945
Feb 27 19:35:40 io etcd[29184]: restore compact to 13966097
Feb 27 19:35:40 io etcd[29184]: name = default
Feb 27 19:35:40 io etcd[29184]: data dir = /var/snap/microk8s/common/var/run/etcd
Feb 27 19:35:40 io etcd[29184]: member dir = /var/snap/microk8s/common/var/run/etcd/member
Feb 27 19:35:40 io etcd[29184]: heartbeat = 100ms
Feb 27 19:35:40 io etcd[29184]: election = 1000ms
Feb 27 19:35:40 io etcd[29184]: snapshot count = 100000
Feb 27 19:35:40 io etcd[29184]: advertise client URLs = https://192.168.1.131:12379
Feb 27 19:35:41 io etcd[29184]: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 27524469
Feb 27 19:35:41 io etcd[29184]: 8e9e05c52164694d became follower at term 13042
Feb 27 19:35:41 io etcd[29184]: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 13042, commit: 27524469, applied: 27506945, lastindex: 27524469, lastterm: 13042]
Feb 27 19:35:41 io etcd[29184]: cluster cannot be downgraded (current version: 3.3.4 is lower than determined cluster version: 3.4).
Feb 27 19:35:41 io systemd[1]: snap.microk8s.daemon-etcd.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 19:35:41 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
Feb 27 19:35:41 io systemd[1]: snap.microk8s.daemon-etcd.service: Service RestartSec=100ms expired, scheduling restart.
Feb 27 19:35:41 io systemd[1]: snap.microk8s.daemon-etcd.service: Scheduled restart job, restart counter is at 1.
...skipping...
Feb 27 19:35:48 io etcd[29960]: Git SHA: fdde8705f
Feb 27 19:35:48 io etcd[29960]: Go Version: go1.9.5
Feb 27 19:35:48 io etcd[29960]: Go OS/Arch: linux/arm64
Feb 27 19:35:48 io etcd[29960]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Feb 27 19:35:48 io etcd[29960]: the server is already initialized as member before, starting as etcd member...
Feb 27 19:35:48 io etcd[29960]: listening for peers on http://localhost:2380
Feb 27 19:35:48 io etcd[29960]: listening for client requests on 0.0.0.0:12379
Feb 27 19:35:48 io etcd[29960]: recovered store from snapshot at index 27506945
Feb 27 19:35:48 io etcd[29960]: restore compact to 13966097
Feb 27 19:35:48 io etcd[29960]: name = default
Feb 27 19:35:48 io etcd[29960]: data dir = /var/snap/microk8s/common/var/run/etcd
Feb 27 19:35:48 io etcd[29960]: member dir = /var/snap/microk8s/common/var/run/etcd/member
Feb 27 19:35:48 io etcd[29960]: heartbeat = 100ms
Feb 27 19:35:48 io etcd[29960]: election = 1000ms
Feb 27 19:35:48 io etcd[29960]: snapshot count = 100000
Feb 27 19:35:48 io etcd[29960]: advertise client URLs = https://192.168.1.131:12379
Feb 27 19:35:49 io etcd[29960]: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 27524469
Feb 27 19:35:49 io etcd[29960]: 8e9e05c52164694d became follower at term 13042
Feb 27 19:35:49 io etcd[29960]: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 13042, commit: 27524469, applied: 27506945, lastindex: 27524469, lastterm: 13042]
Feb 27 19:35:49 io etcd[29960]: cluster cannot be downgraded (current version: 3.3.4 is lower than determined cluster version: 3.4).
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Service RestartSec=100ms expired, scheduling restart.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Scheduled restart job, restart counter is at 6.
Feb 27 19:35:50 io systemd[1]: Stopped Service for snap application microk8s.daemon-etcd.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Start request repeated too quickly.
Feb 27 19:35:50 io systemd[1]: snap.microk8s.daemon-etcd.service: Failed with result 'exit-code'.
Feb 27 19:35:50 io systemd[1]: Failed to start Service for snap application microk8s.daemon-etcd.
```

**Comment by ktsakalozos** [comment]
I am sorry I misled you. Etcd 3.4 is not available on the 1.17 track. You will have to stay in the `--channel=candidate`. If you want to move to a specific track you will have to reinstall MicroK8s.

**Comment by timwebster9** [comment]
Not sure I understand - I'm happy to stay on the candidate channel to help debug this.  Do I just need to do `snap refresh microk8s --channel=1.17/candidate`?

Doing that however didn't fix anything.  Let me know if there is anything else I can help with - if not I will just re-install.  However with the apiserver not running - any tips on how to clean up my other nodes?

**Comment by ktsakalozos** [comment]
Thank you for offering your help. I would be grateful if you could move to the candidate channel with:
```
sudo snap refresh microk8s --channel=candidate
``` 
Then see if enabling dns fails: `microk8s.enable dns`.

Based on the error you got during the refresh, enabling dns should fail. It is possible a library is missing but I am not sure which one. If could spot the missing lib we could then package it inside the snap.

**Comment by balchua** [comment]
To do clean install you can `snap remove microk8s` then `snap install microk8s --channel=<choose your channel>`

**Comment by timwebster9** [comment]
Hmmm - just using the candidate channel seems to have fixed it:

```
timw@io:~$ sudo snap refresh microk8s --channel=candidate
microk8s (candidate) v1.17.3 from Canonical✓ refreshed

timw@io:~$ microk8s.enable dns
dns is already enabled

timw@io:~$ microk8s.disable dns
Disabling DNS
Reconfiguring kubelet
Removing DNS manifest
serviceaccount "coredns" deleted
configmap "coredns" deleted
deployment.apps "coredns" deleted
service "kube-dns" deleted
clusterrole.rbac.authorization.k8s.io "coredns" deleted
clusterrolebinding.rbac.authorization.k8s.io "coredns" deleted
Removing argument --cluster-domain from nodes.
Applying to node triton.
Removing argument --cluster-dns from nodes.
Applying to node triton.
Restarting nodes.
Applying to node triton.
DNS is disabled

timw@io:~$ microk8s.enable dns
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
Adding argument --cluster-domain to nodes.
Applying to node triton.
Adding argument --cluster-dns to nodes.
Applying to node triton.
Restarting nodes.
Applying to node triton.
DNS is enabled

timw@io:~$ microk8s.status
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: enabled
fluentd: disabled
gpu: disabled
helm3: disabled
helm: disabled
ingress: disabled
istio: disabled
jaeger: disabled
juju: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: enabled
metrics-server: enabled
prometheus: disabled
rbac: disabled
registry: disabled
storage: enabled

timw@io:~$ microk8s.kubectl get pods -n kube-system
NAME                                     READY   STATUS    RESTARTS   AGE
coredns-7b67f9f8c-wrp52                  1/1     Running   0          3m32s
hostpath-provisioner-7c48f5d96d-d6knj    1/1     Running   4          13d
metrics-server-v0.2.1-8444677bcf-xncfn   2/2     Running   4          13d
```

**Comment by timwebster9** [comment]
However I don't want to stay on the candidate channel forever (but happy to stay on it to help any further debugging).  How do I make this stable?  @ktsakalozos any suggestions?

**Comment by ktsakalozos** [comment]
This is some interesting info you provided @timwebster9. The problem is on the configure hook and not on the enable command. Thank you. I do not have the bandwidth to work on this at the moment so there is no point in keeping this cluster. I would suggest you redeploy using the 1.17/stable channel.

**Comment by tjfontaine** [comment]
I guess by following the examples online I too ended up tracking `latest/stable` not simply `1.17/stable` and so now a refresh happened and my etcd cluster is in some weird/wonky state, during a refresh I can see the apiserver and etcd come up, I can perform queries, but eventually during the refresh it reaches a point where it gives the cluster version error as reported above:

`cluster cannot be downgraded (current version: 3.3.4 is lower than determined cluster version: 3.4).`

However, refreshing to `1.17/stable` or `candidate` does not solve the issue for me.

I'm also in a multi-node configuration.

FWIW, I'm not sure I understand the definition of *stable* for microk8s if your position is:

> Backwards incompatible changes are introduced by the upstream Kubernetes project or by MicroK8s in the latest stable track

Is `latest/stable` considered an oxymoron?

To me, snaps should only be promoted to `stable` IFF they can be refreshed as such from an appropriate previous version. Which should not be incompatible with Kubernetes own notion of how to handle upgrades https://kubernetes.io/docs/setup/release/version-skew-policy/

If what you're saying is true about the default `stable` channel, then should all the getting started materials be changed to a specific version `snap install microk8s --classic --channel=1.17/stable`?

> Made for developers, and great for edge, IoT and appliances.

At this point, I am not sure I can consider `microk8s` ready for a production environment given activity like this can happen on the default `stable` channel.

**Comment by ktsakalozos** [comment]
I understand your frustration @timwebster9. Indeed, the latest/stable may introduce breaking changes. The problem is more or less that using the "latest" of anything introduces instability and is considered an anti-pattern [1, 2]. It is however commonly used. Docker images still have the latest tag and the Kubernetes project announces the latest stable at [3].

For MicroK8s we decided the latest/stable to give you the latest stable upstream Kubernetes and do our best to handle incompatible changes as we move forward. We know this is not always possible. The alternative would be to not have the latest track at all.

We describe tracks and channels in [4] and we do not mention the --channel anywhere else  because we would need to update any entries when new upstream releases come out. For long lasting deployments it would be better to chose a specific k8s version (via --channel). Refreshing from one track to another is discouraged  because refreshes keep the configuration you already have and apply it to the targeted k8s cluster. This might not always work.

For production deployments (in addition to specifying the track to follow) you should also take care of when the updates will hit your cluster [5]. Also consider setting up a snap store proxy to check which updates will reach you.

In your specific case you will need to go back to latest stable with `snap refresh microk8s --channel=latest/stable` or even better redeploy the cluster with a track. It would be also great if you attached the `microk8s.inspect` tarball to show us the weird/wonky state of your cluster.

Thank you

[1] https://stackoverflow.com/questions/27989486/why-is-latest-a-dependency-management-anti-pattern
[2] https://vsupalov.com/docker-latest-tag/  
[3] https://storage.googleapis.com/kubernetes-release/release/stable.txt
[4] https://microk8s.io/docs/setting-snap-channel
[5] https://snapcraft.io/docs/keeping-snaps-up-to-date#heading--controlling-updates

**Comment by timwebster9** [comment]
@ktsakalozos that was a different Tim: @tjfontaine :-)

Meanwhile I've reinstalled using 1.17/stable and all is well 😀
